# Makefile.in generated by automake 1.15.1 from Makefile.am.
# Makefile.  Generated from Makefile.in by configure.

# Copyright (C) 1994-2017 Free Software Foundation, Inc.

# This Makefile.in is free software; the Free Software Foundation
# gives unlimited permission to copy and/or distribute it,
# with or without modifications, as long as this notice is preserved.

# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY, to the extent permitted by law; without
# even the implied warranty of MERCHANTABILITY or FITNESS FOR A
# PARTICULAR PURPOSE.



# library that stores all the calculation procedures for two-loop decoupling

# library that stores all the calculation procedures for two-loop decoupling





am__is_gnu_make = { \
  if test -z '$(MAKELEVEL)'; then \
    false; \
  elif test -n '$(MAKE_HOST)'; then \
    true; \
  elif test -n '$(MAKE_VERSION)' && test -n '$(CURDIR)'; then \
    true; \
  else \
    false; \
  fi; \
}
am__make_running_with_option = \
  case $${target_option-} in \
      ?) ;; \
      *) echo "am__make_running_with_option: internal error: invalid" \
              "target option '$${target_option-}' specified" >&2; \
         exit 1;; \
  esac; \
  has_opt=no; \
  sane_makeflags=$$MAKEFLAGS; \
  if $(am__is_gnu_make); then \
    sane_makeflags=$$MFLAGS; \
  else \
    case $$MAKEFLAGS in \
      *\\[\ \	]*) \
        bs=\\; \
        sane_makeflags=`printf '%s\n' "$$MAKEFLAGS" \
          | sed "s/$$bs$$bs[$$bs $$bs	]*//g"`;; \
    esac; \
  fi; \
  skip_next=no; \
  strip_trailopt () \
  { \
    flg=`printf '%s\n' "$$flg" | sed "s/$$1.*$$//"`; \
  }; \
  for flg in $$sane_makeflags; do \
    test $$skip_next = yes && { skip_next=no; continue; }; \
    case $$flg in \
      *=*|--*) continue;; \
        -*I) strip_trailopt 'I'; skip_next=yes;; \
      -*I?*) strip_trailopt 'I';; \
        -*O) strip_trailopt 'O'; skip_next=yes;; \
      -*O?*) strip_trailopt 'O';; \
        -*l) strip_trailopt 'l'; skip_next=yes;; \
      -*l?*) strip_trailopt 'l';; \
      -[dEDm]) skip_next=yes;; \
      -[JT]) skip_next=yes;; \
    esac; \
    case $$flg in \
      *$$target_option*) has_opt=yes; break;; \
    esac; \
  done; \
  test $$has_opt = yes
am__make_dryrun = (target_option=n; $(am__make_running_with_option))
am__make_keepgoing = (target_option=k; $(am__make_running_with_option))
pkgdatadir = $(datadir)/softsusy
pkgincludedir = $(includedir)/softsusy
pkglibdir = $(libdir)/softsusy
pkglibexecdir = $(libexecdir)/softsusy
am__cd = CDPATH="$${ZSH_VERSION+.}$(PATH_SEPARATOR)" && cd
install_sh_DATA = $(install_sh) -c -m 644
install_sh_PROGRAM = $(install_sh) -c
install_sh_SCRIPT = $(install_sh) -c
INSTALL_HEADER = $(INSTALL_DATA)
transform = $(program_transform_name)
NORMAL_INSTALL = :
PRE_INSTALL = :
POST_INSTALL = :
NORMAL_UNINSTALL = :
PRE_UNINSTALL = :
POST_UNINSTALL = :
build_triplet = x86_64-apple-darwin18.7.0
host_triplet = x86_64-apple-darwin18.7.0
bin_PROGRAMS = softsusy.x$(EXEEXT) softsusy-nmssm.x$(EXEEXT) \
	softpoint.x$(EXEEXT) rpvsoftsusy.x$(EXEEXT) rpvneut.x$(EXEEXT)
EXTRA_PROGRAMS = decay.x$(EXEEXT)
#am__append_1 = -looptools -lgfortran
#am__append_2 = -looptools -lgfortran
#am__append_3 = -looptools -lgfortran
#am__append_4 = -looptools -lgfortran
#am__append_5 = -looptools -lgfortran
#am__append_6 = $(himalayadir)/libHimalaya.a
#am__append_7 = $(himalayadir)/libHimalaya.a
#am__append_8 = $(himalayadir)/libHimalaya.a
#am__append_9 = $(himalayadir)/libHimalaya.a
#am__append_10 = $(himalayadir)/libHimalaya.a
#am__append_11 = -I$(himalayadir)/source/include
#am__append_12 = src/mssm_twoloop_mb.cpp src/mssm_twoloop_mt.cpp \
# src/mssm_twoloop_mtau.cpp src/mssm_twoloop_as.cpp

subdir = .
ACLOCAL_M4 = $(top_srcdir)/aclocal.m4
am__aclocal_m4_deps = $(top_srcdir)/m4/libtool.m4 \
	$(top_srcdir)/m4/ltoptions.m4 $(top_srcdir)/m4/ltsugar.m4 \
	$(top_srcdir)/m4/ltversion.m4 $(top_srcdir)/m4/lt~obsolete.m4 \
	$(top_srcdir)/configure.ac
am__configure_deps = $(am__aclocal_m4_deps) $(CONFIGURE_DEPENDENCIES) \
	$(ACLOCAL_M4)
DIST_COMMON = $(srcdir)/Makefile.am $(top_srcdir)/configure \
	$(am__configure_deps) $(dist_pkgdata_DATA) \
	$(pkginclude_HEADERS) $(am__DIST_COMMON)
am__CONFIG_DISTCLEAN_FILES = config.status config.cache config.log \
 configure.lineno config.status.lineno
mkinstalldirs = $(install_sh) -d
CONFIG_HEADER = $(top_builddir)/Config/config.h
CONFIG_CLEAN_FILES =
CONFIG_CLEAN_VPATH_FILES =
am__vpath_adj_setup = srcdirstrip=`echo "$(srcdir)" | sed 's|.|.|g'`;
am__vpath_adj = case $$p in \
    $(srcdir)/*) f=`echo "$$p" | sed "s|^$$srcdirstrip/||"`;; \
    *) f=$$p;; \
  esac;
am__strip_dir = f=`echo $$p | sed -e 's|^.*/||'`;
am__install_max = 40
am__nobase_strip_setup = \
  srcdirstrip=`echo "$(srcdir)" | sed 's/[].[^$$\\*|]/\\\\&/g'`
am__nobase_strip = \
  for p in $$list; do echo "$$p"; done | sed -e "s|$$srcdirstrip/||"
am__nobase_list = $(am__nobase_strip_setup); \
  for p in $$list; do echo "$$p $$p"; done | \
  sed "s| $$srcdirstrip/| |;"' / .*\//!s/ .*/ ./; s,\( .*\)/[^/]*$$,\1,' | \
  $(AWK) 'BEGIN { files["."] = "" } { files[$$2] = files[$$2] " " $$1; \
    if (++n[$$2] == $(am__install_max)) \
      { print $$2, files[$$2]; n[$$2] = 0; files[$$2] = "" } } \
    END { for (dir in files) print dir, files[dir] }'
am__base_list = \
  sed '$$!N;$$!N;$$!N;$$!N;$$!N;$$!N;$$!N;s/\n/ /g' | \
  sed '$$!N;$$!N;$$!N;$$!N;s/\n/ /g'
am__uninstall_files_from_dir = { \
  test -z "$$files" \
    || { test ! -d "$$dir" && test ! -f "$$dir" && test ! -r "$$dir"; } \
    || { echo " ( cd '$$dir' && rm -f" $$files ")"; \
         $(am__cd) "$$dir" && rm -f $$files; }; \
  }
am__installdirs = "$(DESTDIR)$(libdir)" "$(DESTDIR)$(bindir)" \
	"$(DESTDIR)$(pkgdatadir)" "$(DESTDIR)$(pkgincludedir)"
LTLIBRARIES = $(lib_LTLIBRARIES)
libsoft_la_LIBADD =
am__libsoft_la_SOURCES_DIST = src/decays.cpp src/twoBodyDecays.cpp \
	src/threeBodyDecays.cpp src/def.cpp src/linalg.cpp \
	src/lowe.cpp src/numerics.cpp src/rpvneut.cpp src/physpars.cpp \
	src/rge.cpp src/nmssm2loop.f src/dilogwrap.f src/softsusy.cpp \
	src/nmssmsoftsusy.cpp src/nmssmsusy.cpp src/nmssmsoftpars.cpp \
	src/nmssmUtils.cpp src/susy.cpp src/utils.cpp \
	src/mssmUtils.cpp src/softpars.cpp src/nmssmjacobian.cpp \
	src/mssmjacobian.cpp src/tensor.cpp src/rpvsusypars.cpp \
	src/rpvsoft.cpp src/flavoursoft.cpp src/twoloophiggs.f \
	src/mssm_twoloop_mb.cpp src/mssm_twoloop_mt.cpp \
	src/mssm_twoloop_mtau.cpp src/mssm_twoloop_as.cpp
am__dirstamp = $(am__leading_dot)dirstamp
#am__objects_1 =  \
#	src/mssm_twoloop_mb.lo \
#	src/mssm_twoloop_mt.lo \
#	src/mssm_twoloop_mtau.lo \
#	src/mssm_twoloop_as.lo
am_libsoft_la_OBJECTS = src/decays.lo src/twoBodyDecays.lo \
	src/threeBodyDecays.lo src/def.lo src/linalg.lo src/lowe.lo \
	src/numerics.lo src/rpvneut.lo src/physpars.lo src/rge.lo \
	src/nmssm2loop.lo src/dilogwrap.lo src/softsusy.lo \
	src/nmssmsoftsusy.lo src/nmssmsusy.lo src/nmssmsoftpars.lo \
	src/nmssmUtils.lo src/susy.lo src/utils.lo src/mssmUtils.lo \
	src/softpars.lo src/nmssmjacobian.lo src/mssmjacobian.lo \
	src/tensor.lo src/rpvsusypars.lo src/rpvsoft.lo \
	src/flavoursoft.lo src/twoloophiggs.lo $(am__objects_1)
libsoft_la_OBJECTS = $(am_libsoft_la_OBJECTS)
AM_V_lt = $(am__v_lt_$(V))
am__v_lt_ = $(am__v_lt_$(AM_DEFAULT_VERBOSITY))
am__v_lt_0 = --silent
am__v_lt_1 = 
libsoft_la_LINK = $(LIBTOOL) $(AM_V_lt) --tag=CXX $(AM_LIBTOOLFLAGS) \
	$(LIBTOOLFLAGS) --mode=link $(CXXLD) $(AM_CXXFLAGS) \
	$(CXXFLAGS) $(libsoft_la_LDFLAGS) $(LDFLAGS) -o $@
libsupermodel_la_LIBADD =
am_libsupermodel_la_OBJECTS = src/supermodel/supermodel/betas.lo \
	src/supermodel/supermodel/functions.lo \
	src/supermodel/supermodel/higherorder.lo \
	src/supermodel/supermodel/linalg_comp.lo \
	src/supermodel/supermodel/linalg_herm.lo \
	src/supermodel/supermodel/pm_gluino.lo \
	src/supermodel/supermodel/pm_squarks.lo \
	src/supermodel/supermodel/RGrun.lo \
	src/supermodel/supermodel/rk6_RG.lo \
	src/supermodel/supermodel/se1_squarks.lo \
	src/supermodel/supermodel/se2_sbot.lo \
	src/supermodel/supermodel/se2_sdL.lo \
	src/supermodel/supermodel/se2_sdR.lo \
	src/supermodel/supermodel/se2_stop.lo \
	src/supermodel/supermodel/se2_suL.lo \
	src/supermodel/supermodel/se2_suR.lo \
	src/supermodel/supermodel/se_gluino.lo \
	src/supermodel/supermodel/self_fermion.lo \
	src/supermodel/supermodel/self_scalar.lo \
	src/supermodel/supermodel/se_top.lo \
	src/supermodel/supermodel/tqli.lo \
	src/supermodel/supermodel/tred2.lo \
	src/supermodel/supermodel/tree_couplings.lo \
	src/supermodel/supermodel/tree_masses.lo
libsupermodel_la_OBJECTS = $(am_libsupermodel_la_OBJECTS)
libtsil_la_LIBADD =
am_libtsil_la_OBJECTS = src/supermodel/tsil/initialize.lo \
	src/supermodel/tsil/evaluate.lo \
	src/supermodel/tsil/fevaluate.lo \
	src/supermodel/tsil/generic.lo src/supermodel/tsil/rk6.lo \
	src/supermodel/tsil/rk5.lo src/supermodel/tsil/functions.lo \
	src/supermodel/tsil/dilog.lo src/supermodel/tsil/trilog.lo \
	src/supermodel/tsil/dBds.lo src/supermodel/tsil/dSds.lo \
	src/supermodel/tsil/dTds.lo src/supermodel/tsil/dUds.lo \
	src/supermodel/tsil/dsMds.lo src/supermodel/tsil/initB.lo \
	src/supermodel/tsil/initS.lo src/supermodel/tsil/initT.lo \
	src/supermodel/tsil/initU.lo src/supermodel/tsil/initV.lo \
	src/supermodel/tsil/initM.lo src/supermodel/tsil/special.lo \
	src/supermodel/tsil/analyticAB.lo \
	src/supermodel/tsil/analyticI.lo \
	src/supermodel/tsil/analyticS.lo \
	src/supermodel/tsil/analyticT.lo \
	src/supermodel/tsil/analyticTbar.lo \
	src/supermodel/tsil/analyticU.lo \
	src/supermodel/tsil/analyticV.lo \
	src/supermodel/tsil/analyticM.lo \
	src/supermodel/tsil/setTbar.lo src/supermodel/tsil/setV.lo \
	src/supermodel/tsil/setbold.lo
libtsil_la_OBJECTS = $(am_libtsil_la_OBJECTS)
PROGRAMS = $(bin_PROGRAMS)
am_decay_x_OBJECTS = src/mainDecay.$(OBJEXT)
decay_x_OBJECTS = $(am_decay_x_OBJECTS)
decay_x_DEPENDENCIES = libsoft.la libsupermodel.la libtsil.la
am_rpvneut_x_OBJECTS = src/rpvneutmain.$(OBJEXT)
rpvneut_x_OBJECTS = $(am_rpvneut_x_OBJECTS)
am__DEPENDENCIES_1 =
rpvneut_x_DEPENDENCIES = libsoft.la $(am__DEPENDENCIES_1) \
	libsupermodel.la libtsil.la $(am__append_10)
am_rpvsoftsusy_x_OBJECTS = src/rpvmain.$(OBJEXT)
rpvsoftsusy_x_OBJECTS = $(am_rpvsoftsusy_x_OBJECTS)
rpvsoftsusy_x_DEPENDENCIES = libsoft.la $(am__DEPENDENCIES_1) \
	libsupermodel.la libtsil.la $(am__append_9)
am_softpoint_x_OBJECTS = src/softpoint.$(OBJEXT)
softpoint_x_OBJECTS = $(am_softpoint_x_OBJECTS)
softpoint_x_DEPENDENCIES = libsoft.la $(am__DEPENDENCIES_1) \
	libsupermodel.la libtsil.la $(am__append_8)
am_softsusy_nmssm_x_OBJECTS = src/main-nmssm.$(OBJEXT)
softsusy_nmssm_x_OBJECTS = $(am_softsusy_nmssm_x_OBJECTS)
softsusy_nmssm_x_DEPENDENCIES = libsoft.la $(am__DEPENDENCIES_1) \
	libsupermodel.la libtsil.la $(am__append_7)
am_softsusy_x_OBJECTS = src/main.$(OBJEXT)
softsusy_x_OBJECTS = $(am_softsusy_x_OBJECTS)
softsusy_x_DEPENDENCIES = libsoft.la $(am__DEPENDENCIES_1) \
	libsupermodel.la libtsil.la $(am__append_6)
AM_V_P = $(am__v_P_$(V))
am__v_P_ = $(am__v_P_$(AM_DEFAULT_VERBOSITY))
am__v_P_0 = false
am__v_P_1 = :
AM_V_GEN = $(am__v_GEN_$(V))
am__v_GEN_ = $(am__v_GEN_$(AM_DEFAULT_VERBOSITY))
am__v_GEN_0 = @echo "  GEN     " $@;
am__v_GEN_1 = 
AM_V_at = $(am__v_at_$(V))
am__v_at_ = $(am__v_at_$(AM_DEFAULT_VERBOSITY))
am__v_at_0 = @
am__v_at_1 = 
DEFAULT_INCLUDES = -I. -I$(top_builddir)/Config
depcomp = $(SHELL) $(top_srcdir)/Config/depcomp
am__depfiles_maybe = depfiles
am__mv = mv -f
COMPILE = $(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) \
	$(CPPFLAGS) $(AM_CFLAGS) $(CFLAGS)
LTCOMPILE = $(LIBTOOL) $(AM_V_lt) --tag=CC $(AM_LIBTOOLFLAGS) \
	$(LIBTOOLFLAGS) --mode=compile $(CC) $(DEFS) \
	$(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) \
	$(AM_CFLAGS) $(CFLAGS)
AM_V_CC = $(am__v_CC_$(V))
am__v_CC_ = $(am__v_CC_$(AM_DEFAULT_VERBOSITY))
am__v_CC_0 = @echo "  CC      " $@;
am__v_CC_1 = 
CCLD = $(CC)
LINK = $(LIBTOOL) $(AM_V_lt) --tag=CC $(AM_LIBTOOLFLAGS) \
	$(LIBTOOLFLAGS) --mode=link $(CCLD) $(AM_CFLAGS) $(CFLAGS) \
	$(AM_LDFLAGS) $(LDFLAGS) -o $@
AM_V_CCLD = $(am__v_CCLD_$(V))
am__v_CCLD_ = $(am__v_CCLD_$(AM_DEFAULT_VERBOSITY))
am__v_CCLD_0 = @echo "  CCLD    " $@;
am__v_CCLD_1 = 
CXXCOMPILE = $(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) \
	$(AM_CPPFLAGS) $(CPPFLAGS) $(AM_CXXFLAGS) $(CXXFLAGS)
LTCXXCOMPILE = $(LIBTOOL) $(AM_V_lt) --tag=CXX $(AM_LIBTOOLFLAGS) \
	$(LIBTOOLFLAGS) --mode=compile $(CXX) $(DEFS) \
	$(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) \
	$(AM_CXXFLAGS) $(CXXFLAGS)
AM_V_CXX = $(am__v_CXX_$(V))
am__v_CXX_ = $(am__v_CXX_$(AM_DEFAULT_VERBOSITY))
am__v_CXX_0 = @echo "  CXX     " $@;
am__v_CXX_1 = 
CXXLD = $(CXX)
CXXLINK = $(LIBTOOL) $(AM_V_lt) --tag=CXX $(AM_LIBTOOLFLAGS) \
	$(LIBTOOLFLAGS) --mode=link $(CXXLD) $(AM_CXXFLAGS) \
	$(CXXFLAGS) $(AM_LDFLAGS) $(LDFLAGS) -o $@
AM_V_CXXLD = $(am__v_CXXLD_$(V))
am__v_CXXLD_ = $(am__v_CXXLD_$(AM_DEFAULT_VERBOSITY))
am__v_CXXLD_0 = @echo "  CXXLD   " $@;
am__v_CXXLD_1 = 
F77COMPILE = $(F77) $(AM_FFLAGS) $(FFLAGS)
LTF77COMPILE = $(LIBTOOL) $(AM_V_lt) --tag=F77 $(AM_LIBTOOLFLAGS) \
	$(LIBTOOLFLAGS) --mode=compile $(F77) $(AM_FFLAGS) $(FFLAGS)
AM_V_F77 = $(am__v_F77_$(V))
am__v_F77_ = $(am__v_F77_$(AM_DEFAULT_VERBOSITY))
am__v_F77_0 = @echo "  F77     " $@;
am__v_F77_1 = 
F77LD = $(F77)
F77LINK = $(LIBTOOL) $(AM_V_lt) --tag=F77 $(AM_LIBTOOLFLAGS) \
	$(LIBTOOLFLAGS) --mode=link $(F77LD) $(AM_FFLAGS) $(FFLAGS) \
	$(AM_LDFLAGS) $(LDFLAGS) -o $@
AM_V_F77LD = $(am__v_F77LD_$(V))
am__v_F77LD_ = $(am__v_F77LD_$(AM_DEFAULT_VERBOSITY))
am__v_F77LD_0 = @echo "  F77LD   " $@;
am__v_F77LD_1 = 
SOURCES = $(libsoft_la_SOURCES) $(libsupermodel_la_SOURCES) \
	$(libtsil_la_SOURCES) $(decay_x_SOURCES) $(rpvneut_x_SOURCES) \
	$(rpvsoftsusy_x_SOURCES) $(softpoint_x_SOURCES) \
	$(softsusy_nmssm_x_SOURCES) $(softsusy_x_SOURCES)
DIST_SOURCES = $(am__libsoft_la_SOURCES_DIST) \
	$(libsupermodel_la_SOURCES) $(libtsil_la_SOURCES) \
	$(decay_x_SOURCES) $(rpvneut_x_SOURCES) \
	$(rpvsoftsusy_x_SOURCES) $(softpoint_x_SOURCES) \
	$(softsusy_nmssm_x_SOURCES) $(softsusy_x_SOURCES)
am__can_run_installinfo = \
  case $$AM_UPDATE_INFO_DIR in \
    n|no|NO) false;; \
    *) (install-info --version) >/dev/null 2>&1;; \
  esac
DATA = $(dist_pkgdata_DATA)
HEADERS = $(pkginclude_HEADERS)
am__tagged_files = $(HEADERS) $(SOURCES) $(TAGS_FILES) $(LISP)
# Read a list of newline-separated strings from the standard input,
# and print each of them once, without duplicates.  Input order is
# *not* preserved.
am__uniquify_input = $(AWK) '\
  BEGIN { nonempty = 0; } \
  { items[$$0] = 1; nonempty = 1; } \
  END { if (nonempty) { for (i in items) print i; }; } \
'
# Make sure the list of sources is unique.  This is necessary because,
# e.g., the same source file might be shared among _SOURCES variables
# for different programs/libraries.
am__define_uniq_tagged_files = \
  list='$(am__tagged_files)'; \
  unique=`for i in $$list; do \
    if test -f "$$i"; then echo $$i; else echo $(srcdir)/$$i; fi; \
  done | $(am__uniquify_input)`
ETAGS = etags
CTAGS = ctags
CSCOPE = cscope
AM_RECURSIVE_TARGETS = cscope
am__DIST_COMMON = $(srcdir)/Makefile.in $(srcdir)/inOutFiles/inOut.amk \
	$(srcdir)/src/softsusy.amk \
	$(srcdir)/src/supermodel/supermodel.amk \
	$(srcdir)/src/supermodel/tsil.amk $(top_srcdir)/Config/ar-lib \
	$(top_srcdir)/Config/compile $(top_srcdir)/Config/config.guess \
	$(top_srcdir)/Config/config.h.in \
	$(top_srcdir)/Config/config.sub $(top_srcdir)/Config/depcomp \
	$(top_srcdir)/Config/install-sh $(top_srcdir)/Config/ltmain.sh \
	$(top_srcdir)/Config/missing COPYING Config/ar-lib \
	Config/compile Config/config.guess Config/config.sub \
	Config/depcomp Config/install-sh Config/ltmain.sh \
	Config/missing INSTALL README TODO
DISTFILES = $(DIST_COMMON) $(DIST_SOURCES) $(TEXINFOS) $(EXTRA_DIST)
distdir = $(PACKAGE)-$(VERSION)
top_distdir = $(distdir)
am__remove_distdir = \
  if test -d "$(distdir)"; then \
    find "$(distdir)" -type d ! -perm -200 -exec chmod u+w {} ';' \
      && rm -rf "$(distdir)" \
      || { sleep 5 && rm -rf "$(distdir)"; }; \
  else :; fi
am__post_remove_distdir = $(am__remove_distdir)
DIST_ARCHIVES = $(distdir).tar.gz
GZIP_ENV = --best
DIST_TARGETS = dist-gzip
distuninstallcheck_listfiles = find . -type f -print
am__distuninstallcheck_listfiles = $(distuninstallcheck_listfiles) \
  | sed 's|^\./|$(prefix)/|' | grep -v '$(infodir)/dir$$'
distcleancheck_listfiles = find . -type f -print
ACLOCAL = ${SHELL} /Users/elliotleonard/depot/softsusy_foo/Config/missing aclocal-1.15
AMTAR = $${TAR-tar}
AM_DEFAULT_VERBOSITY = 1
AR = ar
AUTOCONF = ${SHELL} /Users/elliotleonard/depot/softsusy_foo/Config/missing autoconf
AUTOHEADER = ${SHELL} /Users/elliotleonard/depot/softsusy_foo/Config/missing autoheader
AUTOMAKE = ${SHELL} /Users/elliotleonard/depot/softsusy_foo/Config/missing automake-1.15
AWK = awk
CC = gcc
CCDEPMODE = depmode=gcc3
CFLAGS = -O0 -g -Wall
CPP = gcc -E
CPPFLAGS =  $(am__append_11)
CXX = g++
CXXCPP = g++ -E
CXXDEPMODE = depmode=gcc3
CXXFLAGS = -O0 -g -std=c++14
CYGPATH_W = echo
DEFS = -DHAVE_CONFIG_H
DEPDIR = .deps
DLLTOOL = false
DSYMUTIL = dsymutil
DUMPBIN = 
ECHO_C = \c
ECHO_N = 
ECHO_T = 
EGREP = /usr/bin/grep -E
EXEEXT = 
F77 = gfortran
FFLAGS = -O0
FGREP = /usr/bin/grep -F
FLIBS =  -L/usr/local/Cellar/gcc/9.2.0_3/lib/gcc/9/gcc/x86_64-apple-darwin18/9.2.0 -L/usr/local/Cellar/gcc/9.2.0_3/lib/gcc/9/gcc/x86_64-apple-darwin18/9.2.0/../../.. -lgfortran -lquadmath -lm
GREP = /usr/bin/grep
INSTALL = /usr/bin/install -c
INSTALL_DATA = ${INSTALL} -m 644
INSTALL_PROGRAM = ${INSTALL}
INSTALL_SCRIPT = ${INSTALL}
INSTALL_STRIP_PROGRAM = $(install_sh) -c -s
LD = /Library/Developer/CommandLineTools/usr/bin/ld
LDFLAGS = 
LIBOBJS = 
LIBS = 
LIBTOOL = $(SHELL) $(top_builddir)/libtool
LIPO = lipo
LN_S = ln -s
LTLIBOBJS = 
LT_SYS_LIBRARY_PATH = 
MAKEINFO = ${SHELL} /Users/elliotleonard/depot/softsusy_foo/Config/missing makeinfo
MANIFEST_TOOL = :
MKDIR_P = Config/install-sh -c -d
NM = /usr/bin/nm -B
NMEDIT = nmedit
OBJDUMP = objdump
OBJEXT = o
OTOOL = otool
OTOOL64 = :
PACKAGE = softsusy
PACKAGE_BUGREPORT = B.C.Allanach@damtp.cam.ac.uk
PACKAGE_NAME = softsusy
PACKAGE_STRING = softsusy 4.1.8
PACKAGE_TARNAME = softsusy
PACKAGE_URL = http://softsusy.hepforge.org/
PACKAGE_VERSION = 4.1.8
PATH_SEPARATOR = :
RANLIB = ranlib
SED = /usr/bin/sed
SET_MAKE = 
SHELL = /bin/sh
STRIP = strip
VERSION = 4.1.8
abs_builddir = /Users/elliotleonard/depot/softsusy_foo
abs_srcdir = /Users/elliotleonard/depot/softsusy_foo
abs_top_builddir = /Users/elliotleonard/depot/softsusy_foo
abs_top_srcdir = /Users/elliotleonard/depot/softsusy_foo
ac_ct_AR = ar
ac_ct_CC = gcc
ac_ct_CXX = g++
ac_ct_DUMPBIN = 
ac_ct_F77 = 
am__include = include
am__leading_dot = .
am__quote = 
am__tar = $${TAR-tar} chof - "$$tardir"
am__untar = $${TAR-tar} xf -
bindir = ${exec_prefix}/bin
build = x86_64-apple-darwin18.7.0
build_alias = 
build_cpu = x86_64
build_os = darwin18.7.0
build_vendor = apple
builddir = .
datadir = ${datarootdir}
datarootdir = ${prefix}/share
docdir = ${datarootdir}/doc/${PACKAGE_TARNAME}
dvidir = ${docdir}
exec_prefix = ${prefix}
host = x86_64-apple-darwin18.7.0
host_alias = 
host_cpu = x86_64
host_os = darwin18.7.0
host_vendor = apple
htmldir = ${docdir}
includedir = ${prefix}/include
infodir = ${datarootdir}/info
install_sh = ${SHELL} /Users/elliotleonard/depot/softsusy_foo/Config/install-sh
libdir = ${exec_prefix}/lib
libexecdir = ${exec_prefix}/libexec
localedir = ${datarootdir}/locale
localstatedir = ${prefix}/var
mandir = ${datarootdir}/man
mkdir_p = $(MKDIR_P)
oldincludedir = /usr/include
pdfdir = ${docdir}
prefix = /usr/local
program_transform_name = s,x,x,
psdir = ${docdir}
runstatedir = ${localstatedir}/run
sbindir = ${exec_prefix}/sbin
sharedstatedir = ${prefix}/com
srcdir = .
sysconfdir = ${prefix}/etc
target_alias = 
top_build_prefix = 
top_builddir = .
top_srcdir = .

# Adding comment
lib_LTLIBRARIES = libsoft.la libtsil.la libsupermodel.la
CLEANFILES = $(OUTPUTFILES) *.x
BUILT_SOURCES = 
EXTRA_DIST = src/nmspec.f src/nmh_slhainp.f $(himalayadir)/doc \
	$(himalayadir)/doc/himalaya.conf $(himalayadir)/.gitignore \
	$(himalayadir)/LICENSE $(himalayadir)/README.md \
	$(himalayadir)/source $(himalayadir)/source/hierarchies \
	$(himalayadir)/source/hierarchies/H6bq22g.cpp \
	$(himalayadir)/source/hierarchies/H3.cpp \
	$(himalayadir)/source/hierarchies/H6.cpp \
	$(himalayadir)/source/hierarchies/H9q2.cpp \
	$(himalayadir)/source/hierarchies/H5.cpp \
	$(himalayadir)/source/hierarchies/H9.cpp \
	$(himalayadir)/source/hierarchies/H6b.cpp \
	$(himalayadir)/source/hierarchies/H3q22g.cpp \
	$(himalayadir)/source/hierarchies/H6bq2g2.cpp \
	$(himalayadir)/source/hierarchies/H6g2.cpp \
	$(himalayadir)/source/hierarchies/H6b2qg2.cpp \
	$(himalayadir)/source/hierarchies/HierarchyCalculator.cpp \
	$(himalayadir)/source/hierarchies/H5g1.cpp \
	$(himalayadir)/source/hierarchies/HierarchyObject.cpp \
	$(himalayadir)/source/hierarchies/H4.cpp \
	$(himalayadir)/source/hierarchies/H32q2g.cpp \
	$(himalayadir)/source/example.cpp \
	$(himalayadir)/source/include \
	$(himalayadir)/source/include/hierarchies \
	$(himalayadir)/source/include/hierarchies/H3q22g.hpp \
	$(himalayadir)/source/include/hierarchies/H6.hpp \
	$(himalayadir)/source/include/hierarchies/H6bq22g.hpp \
	$(himalayadir)/source/include/hierarchies/H4.hpp \
	$(himalayadir)/source/include/hierarchies/H6b.hpp \
	$(himalayadir)/source/include/hierarchies/h6b2qg2 \
	$(himalayadir)/source/include/hierarchies/h6b2qg2/sigS2Full.inc \
	$(himalayadir)/source/include/hierarchies/h6b2qg2/sigS12Full.inc \
	$(himalayadir)/source/include/hierarchies/h6b2qg2/sigS1Full.inc \
	$(himalayadir)/source/include/hierarchies/h5 \
	$(himalayadir)/source/include/hierarchies/h5/sigS2Full.inc \
	$(himalayadir)/source/include/hierarchies/h5/sigS12Full.inc \
	$(himalayadir)/source/include/hierarchies/h5/sigS1Full.inc \
	$(himalayadir)/source/include/hierarchies/h6g2 \
	$(himalayadir)/source/include/hierarchies/h6g2/sigS2Full.inc \
	$(himalayadir)/source/include/hierarchies/h6g2/sigS12Full.inc \
	$(himalayadir)/source/include/hierarchies/h6g2/sigS1Full.inc \
	$(himalayadir)/source/include/hierarchies/h9q2 \
	$(himalayadir)/source/include/hierarchies/h9q2/sigS2Full.inc \
	$(himalayadir)/source/include/hierarchies/h9q2/sigS12Full.inc \
	$(himalayadir)/source/include/hierarchies/h9q2/sigS1Full.inc \
	$(himalayadir)/source/include/hierarchies/h3q22g \
	$(himalayadir)/source/include/hierarchies/h3q22g/sigS2Full.inc \
	$(himalayadir)/source/include/hierarchies/h3q22g/sigS12Full.inc \
	$(himalayadir)/source/include/hierarchies/h3q22g/sigS1Full.inc \
	$(himalayadir)/source/include/hierarchies/H32q2g.hpp \
	$(himalayadir)/source/include/hierarchies/h3 \
	$(himalayadir)/source/include/hierarchies/h3/sigS2Full.inc \
	$(himalayadir)/source/include/hierarchies/h3/sigS12Full.inc \
	$(himalayadir)/source/include/hierarchies/h3/sigS1Full.inc \
	$(himalayadir)/source/include/hierarchies/H3.hpp \
	$(himalayadir)/source/include/hierarchies/H6b2qg2.hpp \
	$(himalayadir)/source/include/hierarchies/h6b \
	$(himalayadir)/source/include/hierarchies/h6b/sigS2Full.inc \
	$(himalayadir)/source/include/hierarchies/h6b/sigS12Full.inc \
	$(himalayadir)/source/include/hierarchies/h6b/sigS1Full.inc \
	$(himalayadir)/source/include/hierarchies/h5g1 \
	$(himalayadir)/source/include/hierarchies/h5g1/sigS2Full.inc \
	$(himalayadir)/source/include/hierarchies/h5g1/sigS12Full.inc \
	$(himalayadir)/source/include/hierarchies/h5g1/sigS1Full.inc \
	$(himalayadir)/source/include/hierarchies/H5.hpp \
	$(himalayadir)/source/include/hierarchies/h6bq22g \
	$(himalayadir)/source/include/hierarchies/h6bq22g/sigS2Full.inc \
	$(himalayadir)/source/include/hierarchies/h6bq22g/sigS12Full.inc \
	$(himalayadir)/source/include/hierarchies/h6bq22g/sigS1Full.inc \
	$(himalayadir)/source/include/hierarchies/H6bq2g2.hpp \
	$(himalayadir)/source/include/hierarchies/H9.hpp \
	$(himalayadir)/source/include/hierarchies/H9q2.hpp \
	$(himalayadir)/source/include/hierarchies/H5g1.hpp \
	$(himalayadir)/source/include/hierarchies/H6g2.hpp \
	$(himalayadir)/source/include/hierarchies/h32q2g \
	$(himalayadir)/source/include/hierarchies/h32q2g/sigS2Full.inc \
	$(himalayadir)/source/include/hierarchies/h32q2g/sigS12Full.inc \
	$(himalayadir)/source/include/hierarchies/h32q2g/sigS1Full.inc \
	$(himalayadir)/source/include/hierarchies/h9 \
	$(himalayadir)/source/include/hierarchies/h9/sigS2Full.inc \
	$(himalayadir)/source/include/hierarchies/h9/sigS12Full.inc \
	$(himalayadir)/source/include/hierarchies/h9/sigS1Full.inc \
	$(himalayadir)/source/include/hierarchies/Utils.hpp \
	$(himalayadir)/source/include/hierarchies/h4 \
	$(himalayadir)/source/include/hierarchies/h4/sigS2Full.inc \
	$(himalayadir)/source/include/hierarchies/h4/sigS12Full.inc \
	$(himalayadir)/source/include/hierarchies/h4/sigS1Full.inc \
	$(himalayadir)/source/include/hierarchies/h6 \
	$(himalayadir)/source/include/hierarchies/h6/sigS2Full.inc \
	$(himalayadir)/source/include/hierarchies/h6/sigS12Full.inc \
	$(himalayadir)/source/include/hierarchies/h6/sigS1Full.inc \
	$(himalayadir)/source/include/hierarchies/h6bq2g2 \
	$(himalayadir)/source/include/hierarchies/h6bq2g2/sigS2Full.inc \
	$(himalayadir)/source/include/hierarchies/h6bq2g2/sigS12Full.inc \
	$(himalayadir)/source/include/hierarchies/h6bq2g2/sigS1Full.inc \
	$(himalayadir)/source/include/Himalaya_interface.hpp \
	$(himalayadir)/source/include/HierarchyCalculator.hpp \
	$(himalayadir)/source/include/version.hpp.in \
	$(himalayadir)/source/include/HierarchyObject.hpp \
	$(himalayadir)/source/include/version.hpp \
	$(himalayadir)/source/include/mh2l \
	$(himalayadir)/source/include/mh2l/DSZHiggs.f \
	$(himalayadir)/source/include/mh2l/functs.f \
	$(himalayadir)/CMakeLists.txt
pkginclude_HEADERS = src/supermodel/tsil/internal.h \
	src/supermodel/tsil/tsil_fortran.h \
	src/supermodel/tsil/tsil_global.h \
	src/supermodel/tsil/tsil_names.h \
	src/supermodel/tsil/tsil_testparams.h \
	src/supermodel/tsil/tsil_funcs.h src/supermodel/tsil/tsil.h \
	src/supermodel/tsil/tsil_params.h \
	src/supermodel/supermodel/self_fermion.h \
	src/supermodel/supermodel/self_scalar.h \
	src/supermodel/supermodel/sumo_build.h \
	src/supermodel/supermodel/sumo_linalg.h \
	src/supermodel/supermodel/sumo_params.h \
	src/supermodel/supermodel/sumo_smdata.h \
	src/supermodel/supermodel/sumo_squarks.h \
	src/supermodel/supermodel/supermodel_defs.h \
	src/supermodel/supermodel/supermodel.h \
	src/supermodel/tsil/tsil.h src/decays.h src/twoBodyDecays.h \
	src/threeBodyDecays.h src/particle.h src/mssm_twoloop_mt.h \
	src/mssm_twoloop_mtau.h src/mssm_twoloop_mb.h \
	src/mssm_twoloop_as.h src/def.h src/main.h src/numerics.h \
	src/softpars.h src/mainDecay.h src/susy.h src/linalg.h \
	src/physpars.h src/softpoint.h src/twoloophiggs.h \
	src/nmssm2loop.h src/dilogwrap.h src/lowe.h src/mycomplex.h \
	src/rge.h src/softsusy.h src/utils.h src/mssmUtils.h \
	src/mssmjacobian.h src/rpvsoft.h src/rpvsusypars.h \
	src/tensor.h src/rpvmain.h src/flavoursoft.h src/xpr-base.h \
	src/xpr-matrix.h src/xpr-vector.h src/rpvneut.h \
	src/nmssmsusy.h src/nmssmsoftpars.h src/higher_order.h \
	src/nmssmsoftsusy.h src/nmssmUtils.h src/nmssmjacobian.h
#include doc/doc.amk
dist_pkgdata_DATA = $(INPUTFILES) $(OUTPUTFILES) CHANGES GUIDELINES \
	COPYING $(DOCFILES)
ACLOCAL_AMFLAGS = ${ACLOCAL_FLAGS} -I m4
AUTOMAKE_OPTIONS = subdir-objects
softsusy_x_SOURCES = src/main.cpp 
softsusy_x_LDADD = libsoft.la $(am__append_1) libsupermodel.la \
	libtsil.la $(am__append_6)
softsusy_nmssm_x_SOURCES = src/main-nmssm.cpp 
softsusy_nmssm_x_LDADD = libsoft.la $(am__append_2) libsupermodel.la \
	libtsil.la $(am__append_7)
softpoint_x_SOURCES = src/softpoint.cpp 
softpoint_x_LDADD = libsoft.la $(am__append_3) libsupermodel.la \
	libtsil.la $(am__append_8)
rpvsoftsusy_x_SOURCES = src/rpvmain.cpp 
rpvsoftsusy_x_LDADD = libsoft.la $(am__append_4) libsupermodel.la \
	libtsil.la $(am__append_9)
rpvneut_x_SOURCES = src/rpvneutmain.cpp 
rpvneut_x_LDADD = libsoft.la $(am__append_5) libsupermodel.la \
	libtsil.la $(am__append_10)
decay_x_SOURCES = src/mainDecay.cpp
decay_x_LDADD = libsoft.la libsupermodel.la libtsil.la
libtsil_la_SOURCES = \
src/supermodel/tsil/initialize.c \
src/supermodel/tsil/evaluate.c \
src/supermodel/tsil/fevaluate.c \
src/supermodel/tsil/generic.c \
src/supermodel/tsil/rk6.c \
src/supermodel/tsil/rk5.c \
src/supermodel/tsil/functions.c \
src/supermodel/tsil/dilog.c \
src/supermodel/tsil/trilog.c \
src/supermodel/tsil/dBds.c \
src/supermodel/tsil/dSds.c \
src/supermodel/tsil/dTds.c \
src/supermodel/tsil/dUds.c \
src/supermodel/tsil/dsMds.c \
src/supermodel/tsil/initB.c \
src/supermodel/tsil/initS.c \
src/supermodel/tsil/initT.c \
src/supermodel/tsil/initU.c \
src/supermodel/tsil/initV.c \
src/supermodel/tsil/initM.c \
src/supermodel/tsil/special.c \
src/supermodel/tsil/analyticAB.c \
src/supermodel/tsil/analyticI.c \
src/supermodel/tsil/analyticS.c \
src/supermodel/tsil/analyticT.c \
src/supermodel/tsil/analyticTbar.c \
src/supermodel/tsil/analyticU.c \
src/supermodel/tsil/analyticV.c \
src/supermodel/tsil/analyticM.c \
src/supermodel/tsil/setTbar.c \
src/supermodel/tsil/setV.c \
src/supermodel/tsil/setbold.c

libsupermodel_la_SOURCES = src/supermodel/supermodel/betas.c \
src/supermodel/supermodel/functions.c \
src/supermodel/supermodel/higherorder.c \
src/supermodel/supermodel/linalg_comp.c \
src/supermodel/supermodel/linalg_herm.c \
src/supermodel/supermodel/pm_gluino.c   \
src/supermodel/supermodel/pm_squarks.c  \
src/supermodel/supermodel/RGrun.c       \
src/supermodel/supermodel/rk6_RG.c      \
src/supermodel/supermodel/se1_squarks.c \
src/supermodel/supermodel/se2_sbot.c    \
src/supermodel/supermodel/se2_sdL.c     \
src/supermodel/supermodel/se2_sdR.c     \
src/supermodel/supermodel/se2_stop.c    \
src/supermodel/supermodel/se2_suL.c     \
src/supermodel/supermodel/se2_suR.c     \
src/supermodel/supermodel/se_gluino.c   \
src/supermodel/supermodel/self_fermion.c \
src/supermodel/supermodel/self_scalar.c \
src/supermodel/supermodel/se_top.c      \
src/supermodel/supermodel/tqli.c        \
src/supermodel/supermodel/tred2.c         \
src/supermodel/supermodel/tree_couplings.c  \
src/supermodel/supermodel/tree_masses.c     

himalayadir = $(srcdir)/src/Himalaya-1.0.0
libsoft_la_SOURCES = src/decays.cpp src/twoBodyDecays.cpp \
	src/threeBodyDecays.cpp src/def.cpp src/linalg.cpp \
	src/lowe.cpp src/numerics.cpp src/rpvneut.cpp src/physpars.cpp \
	src/rge.cpp src/nmssm2loop.f src/dilogwrap.f src/softsusy.cpp \
	src/nmssmsoftsusy.cpp src/nmssmsusy.cpp src/nmssmsoftpars.cpp \
	src/nmssmUtils.cpp src/susy.cpp src/utils.cpp \
	src/mssmUtils.cpp src/softpars.cpp src/nmssmjacobian.cpp \
	src/mssmjacobian.cpp src/tensor.cpp src/rpvsusypars.cpp \
	src/rpvsoft.cpp src/flavoursoft.cpp src/twoloophiggs.f \
	$(am__append_12)
libsoft_la_LDFLAGS =  -L/usr/local/Cellar/gcc/9.2.0_3/lib/gcc/9/gcc/x86_64-apple-darwin18/9.2.0 -L/usr/local/Cellar/gcc/9.2.0_3/lib/gcc/9/gcc/x86_64-apple-darwin18/9.2.0/../../.. -lgfortran -lquadmath -lm
DOCFILES = doc/rpcManual.pdf doc/rpvManual.pdf doc/neutManual.pdf \
	   doc/nmssmManual.pdf doc/threeLoop.pdf doc/ho.pdf doc/decays.pdf

TESTOUTPUT = inOutFiles/slha2Output inOutFiles/lesHouchesOutput inOutFiles/rpvHouchesOutput \
inOutFiles/nmssmSLHAZ3Output inOutFiles/nmssmSLHAnoZ3Output

INPUTFILES = inOutFiles/slha2Input inOutFiles/rpvHouchesInput \
inOutFiles/nmssmSLHAZ3Input inOutFiles/nmssmSLHAnoZ3Input \
inOutFiles/lesHouchesInput 

OUTPUTFILES = $(TESTOUTPUT) inOutFiles/neutOutputTest inOutFiles/rpvOutputTest \
inOutFiles/outputTest inOutFiles/outputTest-nmssm

all: $(BUILT_SOURCES)
	$(MAKE) $(AM_MAKEFLAGS) all-am

.SUFFIXES:
.SUFFIXES: .c .cpp .f .lo .o .obj
am--refresh: Makefile
	@:
$(srcdir)/Makefile.in:  $(srcdir)/Makefile.am $(srcdir)/src/softsusy.amk $(srcdir)/src/supermodel/tsil.amk $(srcdir)/src/supermodel/supermodel.amk $(srcdir)/inOutFiles/inOut.amk $(am__configure_deps)
	@for dep in $?; do \
	  case '$(am__configure_deps)' in \
	    *$$dep*) \
	      echo ' cd $(srcdir) && $(AUTOMAKE) --foreign'; \
	      $(am__cd) $(srcdir) && $(AUTOMAKE) --foreign \
		&& exit 0; \
	      exit 1;; \
	  esac; \
	done; \
	echo ' cd $(top_srcdir) && $(AUTOMAKE) --foreign Makefile'; \
	$(am__cd) $(top_srcdir) && \
	  $(AUTOMAKE) --foreign Makefile
Makefile: $(srcdir)/Makefile.in $(top_builddir)/config.status
	@case '$?' in \
	  *config.status*) \
	    echo ' $(SHELL) ./config.status'; \
	    $(SHELL) ./config.status;; \
	  *) \
	    echo ' cd $(top_builddir) && $(SHELL) ./config.status $@ $(am__depfiles_maybe)'; \
	    cd $(top_builddir) && $(SHELL) ./config.status $@ $(am__depfiles_maybe);; \
	esac;
$(srcdir)/src/softsusy.amk $(srcdir)/src/supermodel/tsil.amk $(srcdir)/src/supermodel/supermodel.amk $(srcdir)/inOutFiles/inOut.amk $(am__empty):

$(top_builddir)/config.status: $(top_srcdir)/configure $(CONFIG_STATUS_DEPENDENCIES)
	$(SHELL) ./config.status --recheck

$(top_srcdir)/configure:  $(am__configure_deps)
	$(am__cd) $(srcdir) && $(AUTOCONF)
$(ACLOCAL_M4):  $(am__aclocal_m4_deps)
	$(am__cd) $(srcdir) && $(ACLOCAL) $(ACLOCAL_AMFLAGS)
$(am__aclocal_m4_deps):

Config/config.h: Config/stamp-h1
	@test -f $@ || rm -f Config/stamp-h1
	@test -f $@ || $(MAKE) $(AM_MAKEFLAGS) Config/stamp-h1

Config/stamp-h1: $(top_srcdir)/Config/config.h.in $(top_builddir)/config.status
	@rm -f Config/stamp-h1
	cd $(top_builddir) && $(SHELL) ./config.status Config/config.h
$(top_srcdir)/Config/config.h.in:  $(am__configure_deps) 
	($(am__cd) $(top_srcdir) && $(AUTOHEADER))
	rm -f Config/stamp-h1
	touch $@

distclean-hdr:
	-rm -f Config/config.h Config/stamp-h1

install-libLTLIBRARIES: $(lib_LTLIBRARIES)
	@$(NORMAL_INSTALL)
	@list='$(lib_LTLIBRARIES)'; test -n "$(libdir)" || list=; \
	list2=; for p in $$list; do \
	  if test -f $$p; then \
	    list2="$$list2 $$p"; \
	  else :; fi; \
	done; \
	test -z "$$list2" || { \
	  echo " $(MKDIR_P) '$(DESTDIR)$(libdir)'"; \
	  $(MKDIR_P) "$(DESTDIR)$(libdir)" || exit 1; \
	  echo " $(LIBTOOL) $(AM_LIBTOOLFLAGS) $(LIBTOOLFLAGS) --mode=install $(INSTALL) $(INSTALL_STRIP_FLAG) $$list2 '$(DESTDIR)$(libdir)'"; \
	  $(LIBTOOL) $(AM_LIBTOOLFLAGS) $(LIBTOOLFLAGS) --mode=install $(INSTALL) $(INSTALL_STRIP_FLAG) $$list2 "$(DESTDIR)$(libdir)"; \
	}

uninstall-libLTLIBRARIES:
	@$(NORMAL_UNINSTALL)
	@list='$(lib_LTLIBRARIES)'; test -n "$(libdir)" || list=; \
	for p in $$list; do \
	  $(am__strip_dir) \
	  echo " $(LIBTOOL) $(AM_LIBTOOLFLAGS) $(LIBTOOLFLAGS) --mode=uninstall rm -f '$(DESTDIR)$(libdir)/$$f'"; \
	  $(LIBTOOL) $(AM_LIBTOOLFLAGS) $(LIBTOOLFLAGS) --mode=uninstall rm -f "$(DESTDIR)$(libdir)/$$f"; \
	done

clean-libLTLIBRARIES:
	-test -z "$(lib_LTLIBRARIES)" || rm -f $(lib_LTLIBRARIES)
	@list='$(lib_LTLIBRARIES)'; \
	locs=`for p in $$list; do echo $$p; done | \
	      sed 's|^[^/]*$$|.|; s|/[^/]*$$||; s|$$|/so_locations|' | \
	      sort -u`; \
	test -z "$$locs" || { \
	  echo rm -f $${locs}; \
	  rm -f $${locs}; \
	}
src/$(am__dirstamp):
	@$(MKDIR_P) src
	@: > src/$(am__dirstamp)
src/$(DEPDIR)/$(am__dirstamp):
	@$(MKDIR_P) src/$(DEPDIR)
	@: > src/$(DEPDIR)/$(am__dirstamp)
src/decays.lo: src/$(am__dirstamp) src/$(DEPDIR)/$(am__dirstamp)
src/twoBodyDecays.lo: src/$(am__dirstamp) \
	src/$(DEPDIR)/$(am__dirstamp)
src/threeBodyDecays.lo: src/$(am__dirstamp) \
	src/$(DEPDIR)/$(am__dirstamp)
src/def.lo: src/$(am__dirstamp) src/$(DEPDIR)/$(am__dirstamp)
src/linalg.lo: src/$(am__dirstamp) src/$(DEPDIR)/$(am__dirstamp)
src/lowe.lo: src/$(am__dirstamp) src/$(DEPDIR)/$(am__dirstamp)
src/numerics.lo: src/$(am__dirstamp) src/$(DEPDIR)/$(am__dirstamp)
src/rpvneut.lo: src/$(am__dirstamp) src/$(DEPDIR)/$(am__dirstamp)
src/physpars.lo: src/$(am__dirstamp) src/$(DEPDIR)/$(am__dirstamp)
src/rge.lo: src/$(am__dirstamp) src/$(DEPDIR)/$(am__dirstamp)
src/nmssm2loop.lo: src/$(am__dirstamp) src/$(DEPDIR)/$(am__dirstamp)
src/dilogwrap.lo: src/$(am__dirstamp) src/$(DEPDIR)/$(am__dirstamp)
src/softsusy.lo: src/$(am__dirstamp) src/$(DEPDIR)/$(am__dirstamp)
src/nmssmsoftsusy.lo: src/$(am__dirstamp) \
	src/$(DEPDIR)/$(am__dirstamp)
src/nmssmsusy.lo: src/$(am__dirstamp) src/$(DEPDIR)/$(am__dirstamp)
src/nmssmsoftpars.lo: src/$(am__dirstamp) \
	src/$(DEPDIR)/$(am__dirstamp)
src/nmssmUtils.lo: src/$(am__dirstamp) src/$(DEPDIR)/$(am__dirstamp)
src/susy.lo: src/$(am__dirstamp) src/$(DEPDIR)/$(am__dirstamp)
src/utils.lo: src/$(am__dirstamp) src/$(DEPDIR)/$(am__dirstamp)
src/mssmUtils.lo: src/$(am__dirstamp) src/$(DEPDIR)/$(am__dirstamp)
src/softpars.lo: src/$(am__dirstamp) src/$(DEPDIR)/$(am__dirstamp)
src/nmssmjacobian.lo: src/$(am__dirstamp) \
	src/$(DEPDIR)/$(am__dirstamp)
src/mssmjacobian.lo: src/$(am__dirstamp) src/$(DEPDIR)/$(am__dirstamp)
src/tensor.lo: src/$(am__dirstamp) src/$(DEPDIR)/$(am__dirstamp)
src/rpvsusypars.lo: src/$(am__dirstamp) src/$(DEPDIR)/$(am__dirstamp)
src/rpvsoft.lo: src/$(am__dirstamp) src/$(DEPDIR)/$(am__dirstamp)
src/flavoursoft.lo: src/$(am__dirstamp) src/$(DEPDIR)/$(am__dirstamp)
src/twoloophiggs.lo: src/$(am__dirstamp) src/$(DEPDIR)/$(am__dirstamp)
src/mssm_twoloop_mb.lo: src/$(am__dirstamp) \
	src/$(DEPDIR)/$(am__dirstamp)
src/mssm_twoloop_mt.lo: src/$(am__dirstamp) \
	src/$(DEPDIR)/$(am__dirstamp)
src/mssm_twoloop_mtau.lo: src/$(am__dirstamp) \
	src/$(DEPDIR)/$(am__dirstamp)
src/mssm_twoloop_as.lo: src/$(am__dirstamp) \
	src/$(DEPDIR)/$(am__dirstamp)

libsoft.la: $(libsoft_la_OBJECTS) $(libsoft_la_DEPENDENCIES) $(EXTRA_libsoft_la_DEPENDENCIES) 
	$(AM_V_CXXLD)$(libsoft_la_LINK) -rpath $(libdir) $(libsoft_la_OBJECTS) $(libsoft_la_LIBADD) $(LIBS)
src/supermodel/supermodel/$(am__dirstamp):
	@$(MKDIR_P) src/supermodel/supermodel
	@: > src/supermodel/supermodel/$(am__dirstamp)
src/supermodel/supermodel/$(DEPDIR)/$(am__dirstamp):
	@$(MKDIR_P) src/supermodel/supermodel/$(DEPDIR)
	@: > src/supermodel/supermodel/$(DEPDIR)/$(am__dirstamp)
src/supermodel/supermodel/betas.lo:  \
	src/supermodel/supermodel/$(am__dirstamp) \
	src/supermodel/supermodel/$(DEPDIR)/$(am__dirstamp)
src/supermodel/supermodel/functions.lo:  \
	src/supermodel/supermodel/$(am__dirstamp) \
	src/supermodel/supermodel/$(DEPDIR)/$(am__dirstamp)
src/supermodel/supermodel/higherorder.lo:  \
	src/supermodel/supermodel/$(am__dirstamp) \
	src/supermodel/supermodel/$(DEPDIR)/$(am__dirstamp)
src/supermodel/supermodel/linalg_comp.lo:  \
	src/supermodel/supermodel/$(am__dirstamp) \
	src/supermodel/supermodel/$(DEPDIR)/$(am__dirstamp)
src/supermodel/supermodel/linalg_herm.lo:  \
	src/supermodel/supermodel/$(am__dirstamp) \
	src/supermodel/supermodel/$(DEPDIR)/$(am__dirstamp)
src/supermodel/supermodel/pm_gluino.lo:  \
	src/supermodel/supermodel/$(am__dirstamp) \
	src/supermodel/supermodel/$(DEPDIR)/$(am__dirstamp)
src/supermodel/supermodel/pm_squarks.lo:  \
	src/supermodel/supermodel/$(am__dirstamp) \
	src/supermodel/supermodel/$(DEPDIR)/$(am__dirstamp)
src/supermodel/supermodel/RGrun.lo:  \
	src/supermodel/supermodel/$(am__dirstamp) \
	src/supermodel/supermodel/$(DEPDIR)/$(am__dirstamp)
src/supermodel/supermodel/rk6_RG.lo:  \
	src/supermodel/supermodel/$(am__dirstamp) \
	src/supermodel/supermodel/$(DEPDIR)/$(am__dirstamp)
src/supermodel/supermodel/se1_squarks.lo:  \
	src/supermodel/supermodel/$(am__dirstamp) \
	src/supermodel/supermodel/$(DEPDIR)/$(am__dirstamp)
src/supermodel/supermodel/se2_sbot.lo:  \
	src/supermodel/supermodel/$(am__dirstamp) \
	src/supermodel/supermodel/$(DEPDIR)/$(am__dirstamp)
src/supermodel/supermodel/se2_sdL.lo:  \
	src/supermodel/supermodel/$(am__dirstamp) \
	src/supermodel/supermodel/$(DEPDIR)/$(am__dirstamp)
src/supermodel/supermodel/se2_sdR.lo:  \
	src/supermodel/supermodel/$(am__dirstamp) \
	src/supermodel/supermodel/$(DEPDIR)/$(am__dirstamp)
src/supermodel/supermodel/se2_stop.lo:  \
	src/supermodel/supermodel/$(am__dirstamp) \
	src/supermodel/supermodel/$(DEPDIR)/$(am__dirstamp)
src/supermodel/supermodel/se2_suL.lo:  \
	src/supermodel/supermodel/$(am__dirstamp) \
	src/supermodel/supermodel/$(DEPDIR)/$(am__dirstamp)
src/supermodel/supermodel/se2_suR.lo:  \
	src/supermodel/supermodel/$(am__dirstamp) \
	src/supermodel/supermodel/$(DEPDIR)/$(am__dirstamp)
src/supermodel/supermodel/se_gluino.lo:  \
	src/supermodel/supermodel/$(am__dirstamp) \
	src/supermodel/supermodel/$(DEPDIR)/$(am__dirstamp)
src/supermodel/supermodel/self_fermion.lo:  \
	src/supermodel/supermodel/$(am__dirstamp) \
	src/supermodel/supermodel/$(DEPDIR)/$(am__dirstamp)
src/supermodel/supermodel/self_scalar.lo:  \
	src/supermodel/supermodel/$(am__dirstamp) \
	src/supermodel/supermodel/$(DEPDIR)/$(am__dirstamp)
src/supermodel/supermodel/se_top.lo:  \
	src/supermodel/supermodel/$(am__dirstamp) \
	src/supermodel/supermodel/$(DEPDIR)/$(am__dirstamp)
src/supermodel/supermodel/tqli.lo:  \
	src/supermodel/supermodel/$(am__dirstamp) \
	src/supermodel/supermodel/$(DEPDIR)/$(am__dirstamp)
src/supermodel/supermodel/tred2.lo:  \
	src/supermodel/supermodel/$(am__dirstamp) \
	src/supermodel/supermodel/$(DEPDIR)/$(am__dirstamp)
src/supermodel/supermodel/tree_couplings.lo:  \
	src/supermodel/supermodel/$(am__dirstamp) \
	src/supermodel/supermodel/$(DEPDIR)/$(am__dirstamp)
src/supermodel/supermodel/tree_masses.lo:  \
	src/supermodel/supermodel/$(am__dirstamp) \
	src/supermodel/supermodel/$(DEPDIR)/$(am__dirstamp)

libsupermodel.la: $(libsupermodel_la_OBJECTS) $(libsupermodel_la_DEPENDENCIES) $(EXTRA_libsupermodel_la_DEPENDENCIES) 
	$(AM_V_CCLD)$(LINK) -rpath $(libdir) $(libsupermodel_la_OBJECTS) $(libsupermodel_la_LIBADD) $(LIBS)
src/supermodel/tsil/$(am__dirstamp):
	@$(MKDIR_P) src/supermodel/tsil
	@: > src/supermodel/tsil/$(am__dirstamp)
src/supermodel/tsil/$(DEPDIR)/$(am__dirstamp):
	@$(MKDIR_P) src/supermodel/tsil/$(DEPDIR)
	@: > src/supermodel/tsil/$(DEPDIR)/$(am__dirstamp)
src/supermodel/tsil/initialize.lo:  \
	src/supermodel/tsil/$(am__dirstamp) \
	src/supermodel/tsil/$(DEPDIR)/$(am__dirstamp)
src/supermodel/tsil/evaluate.lo: src/supermodel/tsil/$(am__dirstamp) \
	src/supermodel/tsil/$(DEPDIR)/$(am__dirstamp)
src/supermodel/tsil/fevaluate.lo: src/supermodel/tsil/$(am__dirstamp) \
	src/supermodel/tsil/$(DEPDIR)/$(am__dirstamp)
src/supermodel/tsil/generic.lo: src/supermodel/tsil/$(am__dirstamp) \
	src/supermodel/tsil/$(DEPDIR)/$(am__dirstamp)
src/supermodel/tsil/rk6.lo: src/supermodel/tsil/$(am__dirstamp) \
	src/supermodel/tsil/$(DEPDIR)/$(am__dirstamp)
src/supermodel/tsil/rk5.lo: src/supermodel/tsil/$(am__dirstamp) \
	src/supermodel/tsil/$(DEPDIR)/$(am__dirstamp)
src/supermodel/tsil/functions.lo: src/supermodel/tsil/$(am__dirstamp) \
	src/supermodel/tsil/$(DEPDIR)/$(am__dirstamp)
src/supermodel/tsil/dilog.lo: src/supermodel/tsil/$(am__dirstamp) \
	src/supermodel/tsil/$(DEPDIR)/$(am__dirstamp)
src/supermodel/tsil/trilog.lo: src/supermodel/tsil/$(am__dirstamp) \
	src/supermodel/tsil/$(DEPDIR)/$(am__dirstamp)
src/supermodel/tsil/dBds.lo: src/supermodel/tsil/$(am__dirstamp) \
	src/supermodel/tsil/$(DEPDIR)/$(am__dirstamp)
src/supermodel/tsil/dSds.lo: src/supermodel/tsil/$(am__dirstamp) \
	src/supermodel/tsil/$(DEPDIR)/$(am__dirstamp)
src/supermodel/tsil/dTds.lo: src/supermodel/tsil/$(am__dirstamp) \
	src/supermodel/tsil/$(DEPDIR)/$(am__dirstamp)
src/supermodel/tsil/dUds.lo: src/supermodel/tsil/$(am__dirstamp) \
	src/supermodel/tsil/$(DEPDIR)/$(am__dirstamp)
src/supermodel/tsil/dsMds.lo: src/supermodel/tsil/$(am__dirstamp) \
	src/supermodel/tsil/$(DEPDIR)/$(am__dirstamp)
src/supermodel/tsil/initB.lo: src/supermodel/tsil/$(am__dirstamp) \
	src/supermodel/tsil/$(DEPDIR)/$(am__dirstamp)
src/supermodel/tsil/initS.lo: src/supermodel/tsil/$(am__dirstamp) \
	src/supermodel/tsil/$(DEPDIR)/$(am__dirstamp)
src/supermodel/tsil/initT.lo: src/supermodel/tsil/$(am__dirstamp) \
	src/supermodel/tsil/$(DEPDIR)/$(am__dirstamp)
src/supermodel/tsil/initU.lo: src/supermodel/tsil/$(am__dirstamp) \
	src/supermodel/tsil/$(DEPDIR)/$(am__dirstamp)
src/supermodel/tsil/initV.lo: src/supermodel/tsil/$(am__dirstamp) \
	src/supermodel/tsil/$(DEPDIR)/$(am__dirstamp)
src/supermodel/tsil/initM.lo: src/supermodel/tsil/$(am__dirstamp) \
	src/supermodel/tsil/$(DEPDIR)/$(am__dirstamp)
src/supermodel/tsil/special.lo: src/supermodel/tsil/$(am__dirstamp) \
	src/supermodel/tsil/$(DEPDIR)/$(am__dirstamp)
src/supermodel/tsil/analyticAB.lo:  \
	src/supermodel/tsil/$(am__dirstamp) \
	src/supermodel/tsil/$(DEPDIR)/$(am__dirstamp)
src/supermodel/tsil/analyticI.lo: src/supermodel/tsil/$(am__dirstamp) \
	src/supermodel/tsil/$(DEPDIR)/$(am__dirstamp)
src/supermodel/tsil/analyticS.lo: src/supermodel/tsil/$(am__dirstamp) \
	src/supermodel/tsil/$(DEPDIR)/$(am__dirstamp)
src/supermodel/tsil/analyticT.lo: src/supermodel/tsil/$(am__dirstamp) \
	src/supermodel/tsil/$(DEPDIR)/$(am__dirstamp)
src/supermodel/tsil/analyticTbar.lo:  \
	src/supermodel/tsil/$(am__dirstamp) \
	src/supermodel/tsil/$(DEPDIR)/$(am__dirstamp)
src/supermodel/tsil/analyticU.lo: src/supermodel/tsil/$(am__dirstamp) \
	src/supermodel/tsil/$(DEPDIR)/$(am__dirstamp)
src/supermodel/tsil/analyticV.lo: src/supermodel/tsil/$(am__dirstamp) \
	src/supermodel/tsil/$(DEPDIR)/$(am__dirstamp)
src/supermodel/tsil/analyticM.lo: src/supermodel/tsil/$(am__dirstamp) \
	src/supermodel/tsil/$(DEPDIR)/$(am__dirstamp)
src/supermodel/tsil/setTbar.lo: src/supermodel/tsil/$(am__dirstamp) \
	src/supermodel/tsil/$(DEPDIR)/$(am__dirstamp)
src/supermodel/tsil/setV.lo: src/supermodel/tsil/$(am__dirstamp) \
	src/supermodel/tsil/$(DEPDIR)/$(am__dirstamp)
src/supermodel/tsil/setbold.lo: src/supermodel/tsil/$(am__dirstamp) \
	src/supermodel/tsil/$(DEPDIR)/$(am__dirstamp)

libtsil.la: $(libtsil_la_OBJECTS) $(libtsil_la_DEPENDENCIES) $(EXTRA_libtsil_la_DEPENDENCIES) 
	$(AM_V_CCLD)$(LINK) -rpath $(libdir) $(libtsil_la_OBJECTS) $(libtsil_la_LIBADD) $(LIBS)
install-binPROGRAMS: $(bin_PROGRAMS)
	@$(NORMAL_INSTALL)
	@list='$(bin_PROGRAMS)'; test -n "$(bindir)" || list=; \
	if test -n "$$list"; then \
	  echo " $(MKDIR_P) '$(DESTDIR)$(bindir)'"; \
	  $(MKDIR_P) "$(DESTDIR)$(bindir)" || exit 1; \
	fi; \
	for p in $$list; do echo "$$p $$p"; done | \
	sed 's/$(EXEEXT)$$//' | \
	while read p p1; do if test -f $$p \
	 || test -f $$p1 \
	  ; then echo "$$p"; echo "$$p"; else :; fi; \
	done | \
	sed -e 'p;s,.*/,,;n;h' \
	    -e 's|.*|.|' \
	    -e 'p;x;s,.*/,,;s/$(EXEEXT)$$//;$(transform);s/$$/$(EXEEXT)/' | \
	sed 'N;N;N;s,\n, ,g' | \
	$(AWK) 'BEGIN { files["."] = ""; dirs["."] = 1 } \
	  { d=$$3; if (dirs[d] != 1) { print "d", d; dirs[d] = 1 } \
	    if ($$2 == $$4) files[d] = files[d] " " $$1; \
	    else { print "f", $$3 "/" $$4, $$1; } } \
	  END { for (d in files) print "f", d, files[d] }' | \
	while read type dir files; do \
	    if test "$$dir" = .; then dir=; else dir=/$$dir; fi; \
	    test -z "$$files" || { \
	    echo " $(INSTALL_PROGRAM_ENV) $(LIBTOOL) $(AM_LIBTOOLFLAGS) $(LIBTOOLFLAGS) --mode=install $(INSTALL_PROGRAM) $$files '$(DESTDIR)$(bindir)$$dir'"; \
	    $(INSTALL_PROGRAM_ENV) $(LIBTOOL) $(AM_LIBTOOLFLAGS) $(LIBTOOLFLAGS) --mode=install $(INSTALL_PROGRAM) $$files "$(DESTDIR)$(bindir)$$dir" || exit $$?; \
	    } \
	; done

uninstall-binPROGRAMS:
	@$(NORMAL_UNINSTALL)
	@list='$(bin_PROGRAMS)'; test -n "$(bindir)" || list=; \
	files=`for p in $$list; do echo "$$p"; done | \
	  sed -e 'h;s,^.*/,,;s/$(EXEEXT)$$//;$(transform)' \
	      -e 's/$$/$(EXEEXT)/' \
	`; \
	test -n "$$list" || exit 0; \
	echo " ( cd '$(DESTDIR)$(bindir)' && rm -f" $$files ")"; \
	cd "$(DESTDIR)$(bindir)" && rm -f $$files

clean-binPROGRAMS:
	@list='$(bin_PROGRAMS)'; test -n "$$list" || exit 0; \
	echo " rm -f" $$list; \
	rm -f $$list || exit $$?; \
	test -n "$(EXEEXT)" || exit 0; \
	list=`for p in $$list; do echo "$$p"; done | sed 's/$(EXEEXT)$$//'`; \
	echo " rm -f" $$list; \
	rm -f $$list
src/mainDecay.$(OBJEXT): src/$(am__dirstamp) \
	src/$(DEPDIR)/$(am__dirstamp)

decay.x$(EXEEXT): $(decay_x_OBJECTS) $(decay_x_DEPENDENCIES) $(EXTRA_decay_x_DEPENDENCIES) 
	@rm -f decay.x$(EXEEXT)
	$(AM_V_CXXLD)$(CXXLINK) $(decay_x_OBJECTS) $(decay_x_LDADD) $(LIBS)
src/rpvneutmain.$(OBJEXT): src/$(am__dirstamp) \
	src/$(DEPDIR)/$(am__dirstamp)

rpvneut.x$(EXEEXT): $(rpvneut_x_OBJECTS) $(rpvneut_x_DEPENDENCIES) $(EXTRA_rpvneut_x_DEPENDENCIES) 
	@rm -f rpvneut.x$(EXEEXT)
	$(AM_V_CXXLD)$(CXXLINK) $(rpvneut_x_OBJECTS) $(rpvneut_x_LDADD) $(LIBS)
src/rpvmain.$(OBJEXT): src/$(am__dirstamp) \
	src/$(DEPDIR)/$(am__dirstamp)

rpvsoftsusy.x$(EXEEXT): $(rpvsoftsusy_x_OBJECTS) $(rpvsoftsusy_x_DEPENDENCIES) $(EXTRA_rpvsoftsusy_x_DEPENDENCIES) 
	@rm -f rpvsoftsusy.x$(EXEEXT)
	$(AM_V_CXXLD)$(CXXLINK) $(rpvsoftsusy_x_OBJECTS) $(rpvsoftsusy_x_LDADD) $(LIBS)
src/softpoint.$(OBJEXT): src/$(am__dirstamp) \
	src/$(DEPDIR)/$(am__dirstamp)

softpoint.x$(EXEEXT): $(softpoint_x_OBJECTS) $(softpoint_x_DEPENDENCIES) $(EXTRA_softpoint_x_DEPENDENCIES) 
	@rm -f softpoint.x$(EXEEXT)
	$(AM_V_CXXLD)$(CXXLINK) $(softpoint_x_OBJECTS) $(softpoint_x_LDADD) $(LIBS)
src/main-nmssm.$(OBJEXT): src/$(am__dirstamp) \
	src/$(DEPDIR)/$(am__dirstamp)

softsusy-nmssm.x$(EXEEXT): $(softsusy_nmssm_x_OBJECTS) $(softsusy_nmssm_x_DEPENDENCIES) $(EXTRA_softsusy_nmssm_x_DEPENDENCIES) 
	@rm -f softsusy-nmssm.x$(EXEEXT)
	$(AM_V_CXXLD)$(CXXLINK) $(softsusy_nmssm_x_OBJECTS) $(softsusy_nmssm_x_LDADD) $(LIBS)
src/main.$(OBJEXT): src/$(am__dirstamp) src/$(DEPDIR)/$(am__dirstamp)

softsusy.x$(EXEEXT): $(softsusy_x_OBJECTS) $(softsusy_x_DEPENDENCIES) $(EXTRA_softsusy_x_DEPENDENCIES) 
	@rm -f softsusy.x$(EXEEXT)
	$(AM_V_CXXLD)$(CXXLINK) $(softsusy_x_OBJECTS) $(softsusy_x_LDADD) $(LIBS)

mostlyclean-compile:
	-rm -f *.$(OBJEXT)
	-rm -f src/*.$(OBJEXT)
	-rm -f src/*.lo
	-rm -f src/supermodel/supermodel/*.$(OBJEXT)
	-rm -f src/supermodel/supermodel/*.lo
	-rm -f src/supermodel/tsil/*.$(OBJEXT)
	-rm -f src/supermodel/tsil/*.lo

distclean-compile:
	-rm -f *.tab.c

include src/$(DEPDIR)/decays.Plo
include src/$(DEPDIR)/def.Plo
include src/$(DEPDIR)/flavoursoft.Plo
include src/$(DEPDIR)/linalg.Plo
include src/$(DEPDIR)/lowe.Plo
include src/$(DEPDIR)/main-nmssm.Po
include src/$(DEPDIR)/main.Po
include src/$(DEPDIR)/mainDecay.Po
include src/$(DEPDIR)/mssmUtils.Plo
include src/$(DEPDIR)/mssm_twoloop_as.Plo
include src/$(DEPDIR)/mssm_twoloop_mb.Plo
include src/$(DEPDIR)/mssm_twoloop_mt.Plo
include src/$(DEPDIR)/mssm_twoloop_mtau.Plo
include src/$(DEPDIR)/mssmjacobian.Plo
include src/$(DEPDIR)/nmssmUtils.Plo
include src/$(DEPDIR)/nmssmjacobian.Plo
include src/$(DEPDIR)/nmssmsoftpars.Plo
include src/$(DEPDIR)/nmssmsoftsusy.Plo
include src/$(DEPDIR)/nmssmsusy.Plo
include src/$(DEPDIR)/numerics.Plo
include src/$(DEPDIR)/physpars.Plo
include src/$(DEPDIR)/rge.Plo
include src/$(DEPDIR)/rpvmain.Po
include src/$(DEPDIR)/rpvneut.Plo
include src/$(DEPDIR)/rpvneutmain.Po
include src/$(DEPDIR)/rpvsoft.Plo
include src/$(DEPDIR)/rpvsusypars.Plo
include src/$(DEPDIR)/softpars.Plo
include src/$(DEPDIR)/softpoint.Po
include src/$(DEPDIR)/softsusy.Plo
include src/$(DEPDIR)/susy.Plo
include src/$(DEPDIR)/tensor.Plo
include src/$(DEPDIR)/threeBodyDecays.Plo
include src/$(DEPDIR)/twoBodyDecays.Plo
include src/$(DEPDIR)/utils.Plo
include src/supermodel/supermodel/$(DEPDIR)/RGrun.Plo
include src/supermodel/supermodel/$(DEPDIR)/betas.Plo
include src/supermodel/supermodel/$(DEPDIR)/functions.Plo
include src/supermodel/supermodel/$(DEPDIR)/higherorder.Plo
include src/supermodel/supermodel/$(DEPDIR)/linalg_comp.Plo
include src/supermodel/supermodel/$(DEPDIR)/linalg_herm.Plo
include src/supermodel/supermodel/$(DEPDIR)/pm_gluino.Plo
include src/supermodel/supermodel/$(DEPDIR)/pm_squarks.Plo
include src/supermodel/supermodel/$(DEPDIR)/rk6_RG.Plo
include src/supermodel/supermodel/$(DEPDIR)/se1_squarks.Plo
include src/supermodel/supermodel/$(DEPDIR)/se2_sbot.Plo
include src/supermodel/supermodel/$(DEPDIR)/se2_sdL.Plo
include src/supermodel/supermodel/$(DEPDIR)/se2_sdR.Plo
include src/supermodel/supermodel/$(DEPDIR)/se2_stop.Plo
include src/supermodel/supermodel/$(DEPDIR)/se2_suL.Plo
include src/supermodel/supermodel/$(DEPDIR)/se2_suR.Plo
include src/supermodel/supermodel/$(DEPDIR)/se_gluino.Plo
include src/supermodel/supermodel/$(DEPDIR)/se_top.Plo
include src/supermodel/supermodel/$(DEPDIR)/self_fermion.Plo
include src/supermodel/supermodel/$(DEPDIR)/self_scalar.Plo
include src/supermodel/supermodel/$(DEPDIR)/tqli.Plo
include src/supermodel/supermodel/$(DEPDIR)/tred2.Plo
include src/supermodel/supermodel/$(DEPDIR)/tree_couplings.Plo
include src/supermodel/supermodel/$(DEPDIR)/tree_masses.Plo
include src/supermodel/tsil/$(DEPDIR)/analyticAB.Plo
include src/supermodel/tsil/$(DEPDIR)/analyticI.Plo
include src/supermodel/tsil/$(DEPDIR)/analyticM.Plo
include src/supermodel/tsil/$(DEPDIR)/analyticS.Plo
include src/supermodel/tsil/$(DEPDIR)/analyticT.Plo
include src/supermodel/tsil/$(DEPDIR)/analyticTbar.Plo
include src/supermodel/tsil/$(DEPDIR)/analyticU.Plo
include src/supermodel/tsil/$(DEPDIR)/analyticV.Plo
include src/supermodel/tsil/$(DEPDIR)/dBds.Plo
include src/supermodel/tsil/$(DEPDIR)/dSds.Plo
include src/supermodel/tsil/$(DEPDIR)/dTds.Plo
include src/supermodel/tsil/$(DEPDIR)/dUds.Plo
include src/supermodel/tsil/$(DEPDIR)/dilog.Plo
include src/supermodel/tsil/$(DEPDIR)/dsMds.Plo
include src/supermodel/tsil/$(DEPDIR)/evaluate.Plo
include src/supermodel/tsil/$(DEPDIR)/fevaluate.Plo
include src/supermodel/tsil/$(DEPDIR)/functions.Plo
include src/supermodel/tsil/$(DEPDIR)/generic.Plo
include src/supermodel/tsil/$(DEPDIR)/initB.Plo
include src/supermodel/tsil/$(DEPDIR)/initM.Plo
include src/supermodel/tsil/$(DEPDIR)/initS.Plo
include src/supermodel/tsil/$(DEPDIR)/initT.Plo
include src/supermodel/tsil/$(DEPDIR)/initU.Plo
include src/supermodel/tsil/$(DEPDIR)/initV.Plo
include src/supermodel/tsil/$(DEPDIR)/initialize.Plo
include src/supermodel/tsil/$(DEPDIR)/rk5.Plo
include src/supermodel/tsil/$(DEPDIR)/rk6.Plo
include src/supermodel/tsil/$(DEPDIR)/setTbar.Plo
include src/supermodel/tsil/$(DEPDIR)/setV.Plo
include src/supermodel/tsil/$(DEPDIR)/setbold.Plo
include src/supermodel/tsil/$(DEPDIR)/special.Plo
include src/supermodel/tsil/$(DEPDIR)/trilog.Plo

.c.o:
	$(AM_V_CC)depbase=`echo $@ | sed 's|[^/]*$$|$(DEPDIR)/&|;s|\.o$$||'`;\
	$(COMPILE) -MT $@ -MD -MP -MF $$depbase.Tpo -c -o $@ $< &&\
	$(am__mv) $$depbase.Tpo $$depbase.Po
#	$(AM_V_CC)source='$<' object='$@' libtool=no \
#	DEPDIR=$(DEPDIR) $(CCDEPMODE) $(depcomp) \
#	$(AM_V_CC_no)$(COMPILE) -c -o $@ $<

.c.obj:
	$(AM_V_CC)depbase=`echo $@ | sed 's|[^/]*$$|$(DEPDIR)/&|;s|\.obj$$||'`;\
	$(COMPILE) -MT $@ -MD -MP -MF $$depbase.Tpo -c -o $@ `$(CYGPATH_W) '$<'` &&\
	$(am__mv) $$depbase.Tpo $$depbase.Po
#	$(AM_V_CC)source='$<' object='$@' libtool=no \
#	DEPDIR=$(DEPDIR) $(CCDEPMODE) $(depcomp) \
#	$(AM_V_CC_no)$(COMPILE) -c -o $@ `$(CYGPATH_W) '$<'`

.c.lo:
	$(AM_V_CC)depbase=`echo $@ | sed 's|[^/]*$$|$(DEPDIR)/&|;s|\.lo$$||'`;\
	$(LTCOMPILE) -MT $@ -MD -MP -MF $$depbase.Tpo -c -o $@ $< &&\
	$(am__mv) $$depbase.Tpo $$depbase.Plo
#	$(AM_V_CC)source='$<' object='$@' libtool=yes \
#	DEPDIR=$(DEPDIR) $(CCDEPMODE) $(depcomp) \
#	$(AM_V_CC_no)$(LTCOMPILE) -c -o $@ $<

.cpp.o:
	$(AM_V_CXX)depbase=`echo $@ | sed 's|[^/]*$$|$(DEPDIR)/&|;s|\.o$$||'`;\
	$(CXXCOMPILE) -MT $@ -MD -MP -MF $$depbase.Tpo -c -o $@ $< &&\
	$(am__mv) $$depbase.Tpo $$depbase.Po
#	$(AM_V_CXX)source='$<' object='$@' libtool=no \
#	DEPDIR=$(DEPDIR) $(CXXDEPMODE) $(depcomp) \
#	$(AM_V_CXX_no)$(CXXCOMPILE) -c -o $@ $<

.cpp.obj:
	$(AM_V_CXX)depbase=`echo $@ | sed 's|[^/]*$$|$(DEPDIR)/&|;s|\.obj$$||'`;\
	$(CXXCOMPILE) -MT $@ -MD -MP -MF $$depbase.Tpo -c -o $@ `$(CYGPATH_W) '$<'` &&\
	$(am__mv) $$depbase.Tpo $$depbase.Po
#	$(AM_V_CXX)source='$<' object='$@' libtool=no \
#	DEPDIR=$(DEPDIR) $(CXXDEPMODE) $(depcomp) \
#	$(AM_V_CXX_no)$(CXXCOMPILE) -c -o $@ `$(CYGPATH_W) '$<'`

.cpp.lo:
	$(AM_V_CXX)depbase=`echo $@ | sed 's|[^/]*$$|$(DEPDIR)/&|;s|\.lo$$||'`;\
	$(LTCXXCOMPILE) -MT $@ -MD -MP -MF $$depbase.Tpo -c -o $@ $< &&\
	$(am__mv) $$depbase.Tpo $$depbase.Plo
#	$(AM_V_CXX)source='$<' object='$@' libtool=yes \
#	DEPDIR=$(DEPDIR) $(CXXDEPMODE) $(depcomp) \
#	$(AM_V_CXX_no)$(LTCXXCOMPILE) -c -o $@ $<

.f.o:
	$(AM_V_F77)$(F77COMPILE) -c -o $@ $<

.f.obj:
	$(AM_V_F77)$(F77COMPILE) -c -o $@ `$(CYGPATH_W) '$<'`

.f.lo:
	$(AM_V_F77)$(LTF77COMPILE) -c -o $@ $<

mostlyclean-libtool:
	-rm -f *.lo

clean-libtool:
	-rm -rf .libs _libs
	-rm -rf src/.libs src/_libs
	-rm -rf src/supermodel/supermodel/.libs src/supermodel/supermodel/_libs
	-rm -rf src/supermodel/tsil/.libs src/supermodel/tsil/_libs

distclean-libtool:
	-rm -f libtool config.lt
install-dist_pkgdataDATA: $(dist_pkgdata_DATA)
	@$(NORMAL_INSTALL)
	@list='$(dist_pkgdata_DATA)'; test -n "$(pkgdatadir)" || list=; \
	if test -n "$$list"; then \
	  echo " $(MKDIR_P) '$(DESTDIR)$(pkgdatadir)'"; \
	  $(MKDIR_P) "$(DESTDIR)$(pkgdatadir)" || exit 1; \
	fi; \
	for p in $$list; do \
	  if test -f "$$p"; then d=; else d="$(srcdir)/"; fi; \
	  echo "$$d$$p"; \
	done | $(am__base_list) | \
	while read files; do \
	  echo " $(INSTALL_DATA) $$files '$(DESTDIR)$(pkgdatadir)'"; \
	  $(INSTALL_DATA) $$files "$(DESTDIR)$(pkgdatadir)" || exit $$?; \
	done

uninstall-dist_pkgdataDATA:
	@$(NORMAL_UNINSTALL)
	@list='$(dist_pkgdata_DATA)'; test -n "$(pkgdatadir)" || list=; \
	files=`for p in $$list; do echo $$p; done | sed -e 's|^.*/||'`; \
	dir='$(DESTDIR)$(pkgdatadir)'; $(am__uninstall_files_from_dir)
install-pkgincludeHEADERS: $(pkginclude_HEADERS)
	@$(NORMAL_INSTALL)
	@list='$(pkginclude_HEADERS)'; test -n "$(pkgincludedir)" || list=; \
	if test -n "$$list"; then \
	  echo " $(MKDIR_P) '$(DESTDIR)$(pkgincludedir)'"; \
	  $(MKDIR_P) "$(DESTDIR)$(pkgincludedir)" || exit 1; \
	fi; \
	for p in $$list; do \
	  if test -f "$$p"; then d=; else d="$(srcdir)/"; fi; \
	  echo "$$d$$p"; \
	done | $(am__base_list) | \
	while read files; do \
	  echo " $(INSTALL_HEADER) $$files '$(DESTDIR)$(pkgincludedir)'"; \
	  $(INSTALL_HEADER) $$files "$(DESTDIR)$(pkgincludedir)" || exit $$?; \
	done

uninstall-pkgincludeHEADERS:
	@$(NORMAL_UNINSTALL)
	@list='$(pkginclude_HEADERS)'; test -n "$(pkgincludedir)" || list=; \
	files=`for p in $$list; do echo $$p; done | sed -e 's|^.*/||'`; \
	dir='$(DESTDIR)$(pkgincludedir)'; $(am__uninstall_files_from_dir)

ID: $(am__tagged_files)
	$(am__define_uniq_tagged_files); mkid -fID $$unique
tags: tags-am
TAGS: tags

tags-am: $(TAGS_DEPENDENCIES) $(am__tagged_files)
	set x; \
	here=`pwd`; \
	$(am__define_uniq_tagged_files); \
	shift; \
	if test -z "$(ETAGS_ARGS)$$*$$unique"; then :; else \
	  test -n "$$unique" || unique=$$empty_fix; \
	  if test $$# -gt 0; then \
	    $(ETAGS) $(ETAGSFLAGS) $(AM_ETAGSFLAGS) $(ETAGS_ARGS) \
	      "$$@" $$unique; \
	  else \
	    $(ETAGS) $(ETAGSFLAGS) $(AM_ETAGSFLAGS) $(ETAGS_ARGS) \
	      $$unique; \
	  fi; \
	fi
ctags: ctags-am

CTAGS: ctags
ctags-am: $(TAGS_DEPENDENCIES) $(am__tagged_files)
	$(am__define_uniq_tagged_files); \
	test -z "$(CTAGS_ARGS)$$unique" \
	  || $(CTAGS) $(CTAGSFLAGS) $(AM_CTAGSFLAGS) $(CTAGS_ARGS) \
	     $$unique

GTAGS:
	here=`$(am__cd) $(top_builddir) && pwd` \
	  && $(am__cd) $(top_srcdir) \
	  && gtags -i $(GTAGS_ARGS) "$$here"
cscope: cscope.files
	test ! -s cscope.files \
	  || $(CSCOPE) -b -q $(AM_CSCOPEFLAGS) $(CSCOPEFLAGS) -i cscope.files $(CSCOPE_ARGS)
clean-cscope:
	-rm -f cscope.files
cscope.files: clean-cscope cscopelist
cscopelist: cscopelist-am

cscopelist-am: $(am__tagged_files)
	list='$(am__tagged_files)'; \
	case "$(srcdir)" in \
	  [\\/]* | ?:[\\/]*) sdir="$(srcdir)" ;; \
	  *) sdir=$(subdir)/$(srcdir) ;; \
	esac; \
	for i in $$list; do \
	  if test -f "$$i"; then \
	    echo "$(subdir)/$$i"; \
	  else \
	    echo "$$sdir/$$i"; \
	  fi; \
	done >> $(top_builddir)/cscope.files

distclean-tags:
	-rm -f TAGS ID GTAGS GRTAGS GSYMS GPATH tags
	-rm -f cscope.out cscope.in.out cscope.po.out cscope.files

distdir: $(DISTFILES)
	$(am__remove_distdir)
	test -d "$(distdir)" || mkdir "$(distdir)"
	@srcdirstrip=`echo "$(srcdir)" | sed 's/[].[^$$\\*]/\\\\&/g'`; \
	topsrcdirstrip=`echo "$(top_srcdir)" | sed 's/[].[^$$\\*]/\\\\&/g'`; \
	list='$(DISTFILES)'; \
	  dist_files=`for file in $$list; do echo $$file; done | \
	  sed -e "s|^$$srcdirstrip/||;t" \
	      -e "s|^$$topsrcdirstrip/|$(top_builddir)/|;t"`; \
	case $$dist_files in \
	  */*) $(MKDIR_P) `echo "$$dist_files" | \
			   sed '/\//!d;s|^|$(distdir)/|;s,/[^/]*$$,,' | \
			   sort -u` ;; \
	esac; \
	for file in $$dist_files; do \
	  if test -f $$file || test -d $$file; then d=.; else d=$(srcdir); fi; \
	  if test -d $$d/$$file; then \
	    dir=`echo "/$$file" | sed -e 's,/[^/]*$$,,'`; \
	    if test -d "$(distdir)/$$file"; then \
	      find "$(distdir)/$$file" -type d ! -perm -700 -exec chmod u+rwx {} \;; \
	    fi; \
	    if test -d $(srcdir)/$$file && test $$d != $(srcdir); then \
	      cp -fpR $(srcdir)/$$file "$(distdir)$$dir" || exit 1; \
	      find "$(distdir)/$$file" -type d ! -perm -700 -exec chmod u+rwx {} \;; \
	    fi; \
	    cp -fpR $$d/$$file "$(distdir)$$dir" || exit 1; \
	  else \
	    test -f "$(distdir)/$$file" \
	    || cp -p $$d/$$file "$(distdir)/$$file" \
	    || exit 1; \
	  fi; \
	done
	$(MAKE) $(AM_MAKEFLAGS) \
	  top_distdir="$(top_distdir)" distdir="$(distdir)" \
	  dist-hook
	-test -n "$(am__skip_mode_fix)" \
	|| find "$(distdir)" -type d ! -perm -755 \
		-exec chmod u+rwx,go+rx {} \; -o \
	  ! -type d ! -perm -444 -links 1 -exec chmod a+r {} \; -o \
	  ! -type d ! -perm -400 -exec chmod a+r {} \; -o \
	  ! -type d ! -perm -444 -exec $(install_sh) -c -m a+r {} {} \; \
	|| chmod -R a+r "$(distdir)"
dist-gzip: distdir
	tardir=$(distdir) && $(am__tar) | eval GZIP= gzip $(GZIP_ENV) -c >$(distdir).tar.gz
	$(am__post_remove_distdir)

dist-bzip2: distdir
	tardir=$(distdir) && $(am__tar) | BZIP2=$${BZIP2--9} bzip2 -c >$(distdir).tar.bz2
	$(am__post_remove_distdir)

dist-lzip: distdir
	tardir=$(distdir) && $(am__tar) | lzip -c $${LZIP_OPT--9} >$(distdir).tar.lz
	$(am__post_remove_distdir)

dist-xz: distdir
	tardir=$(distdir) && $(am__tar) | XZ_OPT=$${XZ_OPT--e} xz -c >$(distdir).tar.xz
	$(am__post_remove_distdir)

dist-tarZ: distdir
	@echo WARNING: "Support for distribution archives compressed with" \
		       "legacy program 'compress' is deprecated." >&2
	@echo WARNING: "It will be removed altogether in Automake 2.0" >&2
	tardir=$(distdir) && $(am__tar) | compress -c >$(distdir).tar.Z
	$(am__post_remove_distdir)

dist-shar: distdir
	@echo WARNING: "Support for shar distribution archives is" \
	               "deprecated." >&2
	@echo WARNING: "It will be removed altogether in Automake 2.0" >&2
	shar $(distdir) | eval GZIP= gzip $(GZIP_ENV) -c >$(distdir).shar.gz
	$(am__post_remove_distdir)

dist-zip: distdir
	-rm -f $(distdir).zip
	zip -rq $(distdir).zip $(distdir)
	$(am__post_remove_distdir)

dist dist-all:
	$(MAKE) $(AM_MAKEFLAGS) $(DIST_TARGETS) am__post_remove_distdir='@:'
	$(am__post_remove_distdir)

# This target untars the dist file and tries a VPATH configuration.  Then
# it guarantees that the distribution is self-contained by making another
# tarfile.
distcheck: dist
	case '$(DIST_ARCHIVES)' in \
	*.tar.gz*) \
	  eval GZIP= gzip $(GZIP_ENV) -dc $(distdir).tar.gz | $(am__untar) ;;\
	*.tar.bz2*) \
	  bzip2 -dc $(distdir).tar.bz2 | $(am__untar) ;;\
	*.tar.lz*) \
	  lzip -dc $(distdir).tar.lz | $(am__untar) ;;\
	*.tar.xz*) \
	  xz -dc $(distdir).tar.xz | $(am__untar) ;;\
	*.tar.Z*) \
	  uncompress -c $(distdir).tar.Z | $(am__untar) ;;\
	*.shar.gz*) \
	  eval GZIP= gzip $(GZIP_ENV) -dc $(distdir).shar.gz | unshar ;;\
	*.zip*) \
	  unzip $(distdir).zip ;;\
	esac
	chmod -R a-w $(distdir)
	chmod u+w $(distdir)
	mkdir $(distdir)/_build $(distdir)/_build/sub $(distdir)/_inst
	chmod a-w $(distdir)
	test -d $(distdir)/_build || exit 0; \
	dc_install_base=`$(am__cd) $(distdir)/_inst && pwd | sed -e 's,^[^:\\/]:[\\/],/,'` \
	  && dc_destdir="$${TMPDIR-/tmp}/am-dc-$$$$/" \
	  && am__cwd=`pwd` \
	  && $(am__cd) $(distdir)/_build/sub \
	  && ../../configure \
	    $(AM_DISTCHECK_CONFIGURE_FLAGS) \
	    $(DISTCHECK_CONFIGURE_FLAGS) \
	    --srcdir=../.. --prefix="$$dc_install_base" \
	  && $(MAKE) $(AM_MAKEFLAGS) \
	  && $(MAKE) $(AM_MAKEFLAGS) dvi \
	  && $(MAKE) $(AM_MAKEFLAGS) check \
	  && $(MAKE) $(AM_MAKEFLAGS) install \
	  && $(MAKE) $(AM_MAKEFLAGS) installcheck \
	  && $(MAKE) $(AM_MAKEFLAGS) uninstall \
	  && $(MAKE) $(AM_MAKEFLAGS) distuninstallcheck_dir="$$dc_install_base" \
	        distuninstallcheck \
	  && chmod -R a-w "$$dc_install_base" \
	  && ({ \
	       (cd ../.. && umask 077 && mkdir "$$dc_destdir") \
	       && $(MAKE) $(AM_MAKEFLAGS) DESTDIR="$$dc_destdir" install \
	       && $(MAKE) $(AM_MAKEFLAGS) DESTDIR="$$dc_destdir" uninstall \
	       && $(MAKE) $(AM_MAKEFLAGS) DESTDIR="$$dc_destdir" \
	            distuninstallcheck_dir="$$dc_destdir" distuninstallcheck; \
	      } || { rm -rf "$$dc_destdir"; exit 1; }) \
	  && rm -rf "$$dc_destdir" \
	  && $(MAKE) $(AM_MAKEFLAGS) dist \
	  && rm -rf $(DIST_ARCHIVES) \
	  && $(MAKE) $(AM_MAKEFLAGS) distcleancheck \
	  && cd "$$am__cwd" \
	  || exit 1
	$(am__post_remove_distdir)
	@(echo "$(distdir) archives ready for distribution: "; \
	  list='$(DIST_ARCHIVES)'; for i in $$list; do echo $$i; done) | \
	  sed -e 1h -e 1s/./=/g -e 1p -e 1x -e '$$p' -e '$$x'
distuninstallcheck:
	@test -n '$(distuninstallcheck_dir)' || { \
	  echo 'ERROR: trying to run $@ with an empty' \
	       '$$(distuninstallcheck_dir)' >&2; \
	  exit 1; \
	}; \
	$(am__cd) '$(distuninstallcheck_dir)' || { \
	  echo 'ERROR: cannot chdir into $(distuninstallcheck_dir)' >&2; \
	  exit 1; \
	}; \
	test `$(am__distuninstallcheck_listfiles) | wc -l` -eq 0 \
	   || { echo "ERROR: files left after uninstall:" ; \
	        if test -n "$(DESTDIR)"; then \
	          echo "  (check DESTDIR support)"; \
	        fi ; \
	        $(distuninstallcheck_listfiles) ; \
	        exit 1; } >&2
distcleancheck: distclean
	@if test '$(srcdir)' = . ; then \
	  echo "ERROR: distcleancheck can only run from a VPATH build" ; \
	  exit 1 ; \
	fi
	@test `$(distcleancheck_listfiles) | wc -l` -eq 0 \
	  || { echo "ERROR: files left in build directory after distclean:" ; \
	       $(distcleancheck_listfiles) ; \
	       exit 1; } >&2
check-am: all-am
check: $(BUILT_SOURCES)
	$(MAKE) $(AM_MAKEFLAGS) check-am
all-am: Makefile $(LTLIBRARIES) $(PROGRAMS) $(DATA) $(HEADERS)
install-binPROGRAMS: install-libLTLIBRARIES

installdirs:
	for dir in "$(DESTDIR)$(libdir)" "$(DESTDIR)$(bindir)" "$(DESTDIR)$(pkgdatadir)" "$(DESTDIR)$(pkgincludedir)"; do \
	  test -z "$$dir" || $(MKDIR_P) "$$dir"; \
	done
install: $(BUILT_SOURCES)
	$(MAKE) $(AM_MAKEFLAGS) install-am
install-exec: install-exec-am
install-data: install-data-am
uninstall: uninstall-am

install-am: all-am
	@$(MAKE) $(AM_MAKEFLAGS) install-exec-am install-data-am

installcheck: installcheck-am
install-strip:
	if test -z '$(STRIP)'; then \
	  $(MAKE) $(AM_MAKEFLAGS) INSTALL_PROGRAM="$(INSTALL_STRIP_PROGRAM)" \
	    install_sh_PROGRAM="$(INSTALL_STRIP_PROGRAM)" INSTALL_STRIP_FLAG=-s \
	      install; \
	else \
	  $(MAKE) $(AM_MAKEFLAGS) INSTALL_PROGRAM="$(INSTALL_STRIP_PROGRAM)" \
	    install_sh_PROGRAM="$(INSTALL_STRIP_PROGRAM)" INSTALL_STRIP_FLAG=-s \
	    "INSTALL_PROGRAM_ENV=STRIPPROG='$(STRIP)'" install; \
	fi
mostlyclean-generic:

clean-generic:
	-test -z "$(CLEANFILES)" || rm -f $(CLEANFILES)

distclean-generic:
	-test -z "$(CONFIG_CLEAN_FILES)" || rm -f $(CONFIG_CLEAN_FILES)
	-test . = "$(srcdir)" || test -z "$(CONFIG_CLEAN_VPATH_FILES)" || rm -f $(CONFIG_CLEAN_VPATH_FILES)
	-rm -f src/$(DEPDIR)/$(am__dirstamp)
	-rm -f src/$(am__dirstamp)
	-rm -f src/supermodel/supermodel/$(DEPDIR)/$(am__dirstamp)
	-rm -f src/supermodel/supermodel/$(am__dirstamp)
	-rm -f src/supermodel/tsil/$(DEPDIR)/$(am__dirstamp)
	-rm -f src/supermodel/tsil/$(am__dirstamp)

maintainer-clean-generic:
	@echo "This command is intended for maintainers to use"
	@echo "it deletes files that may require special tools to rebuild."
	-test -z "$(BUILT_SOURCES)" || rm -f $(BUILT_SOURCES)
clean: clean-am

clean-am: clean-binPROGRAMS clean-generic clean-libLTLIBRARIES \
	clean-libtool clean-local mostlyclean-am

distclean: distclean-am
	-rm -f $(am__CONFIG_DISTCLEAN_FILES)
	-rm -rf src/$(DEPDIR) src/supermodel/supermodel/$(DEPDIR) src/supermodel/tsil/$(DEPDIR)
	-rm -f Makefile
distclean-am: clean-am distclean-compile distclean-generic \
	distclean-hdr distclean-libtool distclean-tags

dvi: dvi-am

dvi-am:

html: html-am

html-am:

info: info-am

info-am:

install-data-am: install-data-local install-dist_pkgdataDATA \
	install-pkgincludeHEADERS

install-dvi: install-dvi-am

install-dvi-am:

install-exec-am: install-binPROGRAMS install-libLTLIBRARIES

install-html: install-html-am

install-html-am:

install-info: install-info-am

install-info-am:

install-man:

install-pdf: install-pdf-am

install-pdf-am:

install-ps: install-ps-am

install-ps-am:

installcheck-am:

maintainer-clean: maintainer-clean-am
	-rm -f $(am__CONFIG_DISTCLEAN_FILES)
	-rm -rf $(top_srcdir)/autom4te.cache
	-rm -rf src/$(DEPDIR) src/supermodel/supermodel/$(DEPDIR) src/supermodel/tsil/$(DEPDIR)
	-rm -f Makefile
maintainer-clean-am: distclean-am maintainer-clean-generic

mostlyclean: mostlyclean-am

mostlyclean-am: mostlyclean-compile mostlyclean-generic \
	mostlyclean-libtool

pdf: pdf-am

pdf-am:

ps: ps-am

ps-am:

uninstall-am: uninstall-binPROGRAMS uninstall-dist_pkgdataDATA \
	uninstall-libLTLIBRARIES uninstall-pkgincludeHEADERS

.MAKE: all check install install-am install-strip

.PHONY: CTAGS GTAGS TAGS all all-am am--refresh check check-am clean \
	clean-binPROGRAMS clean-cscope clean-generic \
	clean-libLTLIBRARIES clean-libtool clean-local cscope \
	cscopelist-am ctags ctags-am dist dist-all dist-bzip2 \
	dist-gzip dist-hook dist-lzip dist-shar dist-tarZ dist-xz \
	dist-zip distcheck distclean distclean-compile \
	distclean-generic distclean-hdr distclean-libtool \
	distclean-tags distcleancheck distdir distuninstallcheck dvi \
	dvi-am html html-am info info-am install install-am \
	install-binPROGRAMS install-data install-data-am \
	install-data-local install-dist_pkgdataDATA install-dvi \
	install-dvi-am install-exec install-exec-am install-html \
	install-html-am install-info install-info-am \
	install-libLTLIBRARIES install-man install-pdf install-pdf-am \
	install-pkgincludeHEADERS install-ps install-ps-am \
	install-strip installcheck installcheck-am installdirs \
	maintainer-clean maintainer-clean-generic mostlyclean \
	mostlyclean-compile mostlyclean-generic mostlyclean-libtool \
	pdf pdf-am ps ps-am tags tags-am uninstall uninstall-am \
	uninstall-binPROGRAMS uninstall-dist_pkgdataDATA \
	uninstall-libLTLIBRARIES uninstall-pkgincludeHEADERS

.PRECIOUS: Makefile


$(himalayadir)/libHimalaya.a:
	cd $(himalayadir) && cmake . && $(MAKE)
.PHONY: clean-local-himalaya
clean-local: clean-local-himalaya
clean-local-himalaya:
	-$(MAKE) -C $(himalayadir) clean

$(OUTPUTFILES) : inOutFiles/%Output : inOutFiles/%Input softpoint.x 
	$(install_sh) -d inOutFiles
	./softpoint.x leshouches < $< > $@

inOutFiles/outputTest: softsusy.x
	$(install_sh) -d inOutFiles
	./softsusy.x > inOutFiles/outputTest

inOutFiles/outputTest-nmssm: softsusy-nmssm.x
	$(install_sh) -d inOutFiles
	./softsusy-nmssm.x > inOutFiles/outputTest-nmssm

inOutFiles/rpvOutputTest: rpvsoftsusy.x
	$(install_sh) -d inOutFiles
	./rpvsoftsusy.x > inOutFiles/rpvOutputTest

inOutFiles/neutOutputTest: rpvneut.x
	$(install_sh) -d inOutFiles
	./rpvneut.x > inOutFiles/neutOutputTest

test:   softpoint.x
	git checkout $(TESTOUTPUT)
	cp $(TESTOUTPUT) .test; rm $(TESTOUTPUT); make $(TESTOUTPUT); \
	ndiff --relative-error 1.0e-3 inOutFiles/lesHouchesOutput .test/lesHouchesOutput; 
	ndiff --relative-error 1.0e-3 inOutFiles/slha2Output .test/slha2Output; \
	ndiff --relative-error 1.0e-3 inOutFiles/rpvHouchesOutput .test/rpvHouchesOutput; \
	ndiff --relative-error 1.0e-3 inOutFiles/nmssmSLHAZ3Output .test/nmssmSLHAZ3Output; \
	ndiff --relative-error 1.0e-3 inOutFiles/nmssmSLHAnoZ3Output .test/nmssmSLHAnoZ3Output

.PHONY: doc test updateWeb install

nodoc: $(OUTPUTFILES) programs

programs: softpoint.x rpvsoftsusy.x softsusy.x softsusy-nmssm.x rpvneut.x decay.x

updateWeb: dist
	scp -P 222 softsusy-${VERSION}.tar.gz allanach@login.hepforge.org:~/softsusy/downloads; 
	scp -P 222 inOutFiles/*{Input,Output}* allanach@login.hepforge.org:~/softsusy/public_html/code
	scp -P 222 {src/def.h,inOutFiles/outputTest,README} allanach@login.hepforge.org:~/softsusy/public_html/code
	scp -P 222 -r doc/*.pdf allanach@login.hepforge.org:~/softsusy/public_html/doc; \
	doxygen softsusy.cfg &&\
	scp -P 222 -r html allanach@login.hepforge.org:~/softsusy/public_html; \
	scp -P 222 -r CHANGES allanach@login.hepforge.org:~/softsusy/public_html/CHANGES.${VERSION}.html; \
	rm -fr html *.tar.gz

install-data-local:
	rm -f softsusy.x softsusy-nmssm.x softpoint.x rpvsoftsusy.x rpvneut.x *.la

# For distributions: don't re-make the docs
dist-hook:
	sed -i -e 's/^include doc/#include doc/g' $(distdir)/Makefile.am
	rm $(distdir)/doc/doc.amk
	cd $(distdir); autoreconf -vif; cd ..

# Tell versions [3.59,3.63) of GNU make to not export all variables.
# Otherwise a system limit (for SysV at least) may be exceeded.
.NOEXPORT:
